import { StyleSheet } from "react-native"

import { colors } from "@/theme/colors"
import { spacing } from "@/theme/spacing"

export const homeScreenStyles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: colors.pageBackground,
    },
    content: {
        paddingBottom: spacing.lg,
    },
    topGradientSectionWrap: {
        backgroundColor: colors.surface,
        position: "relative",
        zIndex: 5,
    },
    topGradientSectionWrapMenuOpen: {
        zIndex: 80,
    },
    topGradientSection: {
        borderBottomLeftRadius: 28,
        borderBottomRightRadius: 28,
        marginBottom: 0,
        overflow: "hidden",
    },
    topGradientContent: {
        paddingBottom: spacing.md,
        paddingHorizontal: spacing.md,
    },
    homeMenuPopup: {
        right: spacing.md * 2,
    },
    searchInputWrap: {
        alignItems: "center",
        backgroundColor: colors.surface,
        borderRadius: 16,
        flexDirection: "row",
        gap: spacing.sm,
        minHeight: 52,
        paddingHorizontal: spacing.md,
    },
    searchIconWrap: {
        alignItems: "center",
        justifyContent: "center",
    },
    searchInput: {
        color: colors.text,
        flex: 1,
        fontSize: 16,
    },
    searchInputActions: {
        alignItems: "center",
        flexDirection: "row",
        gap: spacing.xs,
        justifyContent: "flex-end",
        minWidth: 34,
        position: "relative",
        zIndex: 95,
    },
    searchPreviewRow: {
        gap: spacing.sm,
        paddingTop: spacing.sm,
    },
    searchPreviewCard: {
        backgroundColor: colors.surface,
        borderRadius: 14,
        maxWidth: 170,
        minWidth: 140,
        overflow: "hidden",
        width: 160,
    },
    searchPreviewCardPressed: {
        opacity: 0.92,
    },
    searchPreviewThumb: {
        backgroundColor: colors.surfaceMuted,
        height: 86,
        width: "100%",
    },
    searchPreviewTitle: {
        color: colors.text,
        fontSize: 13,
        fontWeight: "600",
        paddingHorizontal: spacing.sm,
        paddingVertical: spacing.xs + 2,
    },
    promoBanner: {
        backgroundColor: colors.surface,
        borderRadius: 22,
        overflow: "hidden",
    },
    promoBannerSection: {
        backgroundColor: colors.surface,
        borderBottomLeftRadius: 22,
        borderBottomRightRadius: 22,
        marginBottom: spacing.md,
        overflow: "hidden",
        paddingTop: spacing.md,
        position: "relative",
        zIndex: 1,
    },
    promoBannerPressed: {
        opacity: 0.93,
    },
    promoBannerCarousel: {
        width: "100%",
    },
    promoBannerIndicator: {
        backgroundColor: "rgba(107, 114, 128, 0.3)",
        borderRadius: 999,
        flex: 1,
        height: 2,
    },
    promoBannerIndicatorActive: {
        backgroundColor: "rgba(107, 114, 128, 0.78)",
        flex: 1.7,
        height: 3,
    },
    promoBannerIndicators: {
        alignItems: "center",
        bottom: 0,
        flexDirection: "row",
        gap: spacing.xs,
        justifyContent: "center",
        left: 0,
        position: "absolute",
        right: 0,
    },
    promoBannerTap: {
        backgroundColor: colors.surface,
        borderTopLeftRadius: 22,
        borderTopRightRadius: 22,
        overflow: "hidden",
        width: "100%",
    },
    promoBannerViewport: {
        borderTopLeftRadius: 22,
        borderTopRightRadius: 22,
        overflow: "hidden",
        width: "100%",
    },
    promoImage: {
        aspectRatio: 16 / 9,
        borderTopLeftRadius: 22,
        borderTopRightRadius: 22,
        width: "100%",
    },
    ordersBlock: {
        backgroundColor: colors.surface,
        borderRadius: 24,
        marginBottom: spacing.md,
        paddingBottom: spacing.md,
        paddingHorizontal: spacing.md,
        paddingTop: spacing.md,
    },
    ordersHeader: {
        marginBottom: spacing.sm,
    },
    ordersEyebrow: {
        color: colors.stateText,
        fontSize: 12,
        fontWeight: "700",
        textTransform: "uppercase",
    },
    ordersTitle: {
        color: colors.text,
        fontSize: 20,
        fontWeight: "800",
        marginTop: spacing.xs,
    },
    orderLoginCard: {
        alignItems: "center",
        backgroundColor: colors.primaryMuted,
        borderRadius: 16,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.md,
    },
    orderLoginCardPressed: {
        opacity: 0.92,
    },
    orderLoginCardText: {
        color: colors.primary,
        fontSize: 14,
        fontWeight: "700",
    },
    orderLoadingWrap: {
        alignItems: "center",
        justifyContent: "center",
        minHeight: 80,
    },
    activeOrdersRow: {
        gap: spacing.sm,
    },
    activeOrderCard: {
        alignItems: "flex-start",
        backgroundColor: "#111827",
        borderRadius: 18,
        flexDirection: "row",
        gap: spacing.sm,
        minHeight: 96,
        minWidth: 260,
        padding: spacing.sm,
        width: 304,
    },
    activeOrderCardPressed: {
        opacity: 0.92,
    },
    activeOrderImages: {
        alignContent: "flex-start",
        backgroundColor: "#1F2937",
        borderRadius: 14,
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 4,
        minHeight: 76,
        padding: 4,
        width: 84,
    },
    activeOrderImage: {
        borderRadius: 9,
        height: 36,
        width: 36,
    },
    activeOrderImageSingle: {
        width: 76,
        height: 76,
        borderRadius: 12,
    },
    activeOrderImagePlaceholder: {
        backgroundColor: "#253245",
        borderRadius: 9,
        height: 36,
        width: 36,
    },
    activeOrderBody: {
        flex: 1,
        gap: 6,
        minWidth: 0,
    },
    activeOrderStatusBlock: {
        alignItems: "flex-start",
        gap: 4,
    },
    activeOrderStatusBadge: {
        alignSelf: "flex-start",
        borderRadius: 999,
        maxWidth: "100%",
        paddingHorizontal: 10,
        paddingVertical: 4,
    },
    activeOrderStatusText: {
        fontSize: 12,
        fontWeight: "800",
        lineHeight: 16,
    },
    activeOrderSubtitle: {
        color: "rgba(255,255,255,0.82)",
        fontSize: 14,
        lineHeight: 19,
    },
    activeOrderMeta: {
        color: "rgba(255,255,255,0.65)",
        fontSize: 12,
        fontWeight: "700",
        lineHeight: 16,
    },
    ordersSeparator: {
        backgroundColor: colors.border,
        height: 1,
        marginVertical: spacing.md,
    },
    ordersRow: {
        gap: spacing.sm,
    },
    orderCard: {
        backgroundColor: colors.surfaceMuted,
        borderRadius: 18,
        minWidth: 132,
        position: "relative",
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.md,
        width: 146,
    },
    orderCardPressed: {
        opacity: 0.92,
    },
    orderCardTitle: {
        color: colors.text,
        fontSize: 16,
        fontWeight: "800",
    },
    orderCardMeta: {
        color: colors.stateText,
        fontSize: 13,
        marginTop: spacing.xs,
    },
    orderCardTotal: {
        color: colors.text,
        fontSize: 14,
        fontWeight: "700",
        marginTop: spacing.sm,
    },
    orderCardDeleteBadge: {
        alignItems: "center",
        backgroundColor: "#FDECEF",
        borderRadius: 999,
        borderWidth: 0,
        height: 22,
        justifyContent: "center",
        position: "absolute",
        right: 8,
        top: 8,
        width: 22,
        zIndex: 2,
    },
    orderCardDeleteBadgePressed: {
        opacity: 0.8,
    },
    orderCardDeleteBadgeDisabled: {
        opacity: 0.5,
    },
    orderEmptyCard: {
        backgroundColor: colors.surfaceMuted,
        borderRadius: 16,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.md,
    },
    orderEmptyText: {
        color: colors.stateText,
        fontSize: 13,
        lineHeight: 19,
    },
    recommendationsSection: {
        marginBottom: spacing.md,
    },
    quickCatalogInBanner: {
        backgroundColor: colors.surface,
        paddingBottom: spacing.md,
        paddingTop: spacing.sm,
    },
    quickCatalogRow: {
        flexDirection: "row",
        gap: spacing.sm,
    },
    quickCatalogItem: {
        alignItems: "center",
        width: 78,
    },
    quickCatalogItemPressed: {
        opacity: 0.9,
    },
    quickCatalogIcon: {
        alignItems: "center",
        backgroundColor: colors.primary,
        borderRadius: 14,
        justifyContent: "center",
        marginBottom: spacing.xs,
        overflow: "hidden",
        padding: 8,
        height: 52,
        width: 52,
    },
    quickCatalogLabel: {
        color: colors.text,
        fontSize: 11,
        fontWeight: "600",
        lineHeight: 14,
        textAlign: "center",
        width: 76,
    },
})
