from .env import _bool_env, _env, _int_env


ADMIN_ACCESS_EXPIRE_MINUTES = _int_env("ADMIN_ACCESS_EXPIRE_MINUTES", 15)
ADMIN_CHALLENGE_EXPIRE_MINUTES = _int_env("ADMIN_CHALLENGE_EXPIRE_MINUTES", 10)
ADMIN_COOKIE_SECURE = _bool_env("ADMIN_COOKIE_SECURE", False)
ADMIN_REFRESH_COOKIE_NAME = _env("ADMIN_REFRESH_COOKIE_NAME", "elixir_admin_refresh")
ADMIN_MFA_ISSUER = _env("ADMIN_MFA_ISSUER", "Elixir Shop Admin")
ADMIN_READ_ONLY = _bool_env("ADMIN_READ_ONLY", False)
ADMIN_JOB_QUEUE_NAME = _env("ADMIN_JOB_QUEUE_NAME", "admin:jobs")
ADMIN_JOB_MAX_ATTEMPTS = _int_env("ADMIN_JOB_MAX_ATTEMPTS", 3)
ADMIN_JOB_STALE_SECONDS = _int_env("ADMIN_JOB_STALE_SECONDS", 600)
ADMIN_JOB_RECOVERY_INTERVAL_SECONDS = _int_env("ADMIN_JOB_RECOVERY_INTERVAL_SECONDS", 30)
ADMIN_AUTOMATION_INTERVAL_SECONDS = _int_env("ADMIN_AUTOMATION_INTERVAL_SECONDS", 60)
ADMIN_BACKUP_STATUS_PATH = _env("ADMIN_BACKUP_STATUS_PATH")
ADMIN_PUBLIC_HOST = _env("ADMIN_PUBLIC_HOST", "admin-elixirshop.devsivanschostakov.org")
