from .env import _env, _int_env


AI_CONVERSATION_HARD_INPUT_TOKENS = _int_env("AI_CONVERSATION_HARD_INPUT_TOKENS", 250000)
AI_CONVERSATION_SOFT_INPUT_TOKENS = _int_env("AI_CONVERSATION_SOFT_INPUT_TOKENS", 240000)
AI_CHAT_MAX_ATTACHMENTS = _int_env("AI_CHAT_MAX_ATTACHMENTS", 6)
AI_CHAT_MAX_ATTACHMENT_BYTES = _int_env("AI_CHAT_MAX_ATTACHMENT_BYTES", 10 * 1024 * 1024)
AI_CHAT_MAX_TOTAL_ATTACHMENT_BYTES = _int_env("AI_CHAT_MAX_TOTAL_ATTACHMENT_BYTES", 25 * 1024 * 1024)
AI_CHAT_MAX_AUDIO_BYTES = _int_env("AI_CHAT_MAX_AUDIO_BYTES", 15 * 1024 * 1024)
OPENAI_API_KEY = _env("OPENAI_API_KEY")
OPENAI_PROXY_URL = _env("OPENAI_PROXY_URL")

AI_CHAT_SUSPICIOUS_MESSAGES_PER_MINUTE = _int_env("AI_CHAT_SUSPICIOUS_MESSAGES_PER_MINUTE", 10)
AI_CHAT_SUSPICIOUS_MESSAGES_PER_HOUR = _int_env("AI_CHAT_SUSPICIOUS_MESSAGES_PER_HOUR", 40)
AI_CHAT_SUSPICIOUS_ACCOUNTS_PER_IP_DAY = _int_env("AI_CHAT_SUSPICIOUS_ACCOUNTS_PER_IP_DAY", 5)
