from .env import _env, _int_env


AI_CONVERSATION_HARD_INPUT_TOKENS = _int_env("AI_CONVERSATION_HARD_INPUT_TOKENS", 250000)
AI_CONVERSATION_SOFT_INPUT_TOKENS = _int_env("AI_CONVERSATION_SOFT_INPUT_TOKENS", 240000)
AI_CHAT_MAX_ATTACHMENTS = _int_env("AI_CHAT_MAX_ATTACHMENTS", 6)
AI_CHAT_MAX_ATTACHMENT_BYTES = _int_env("AI_CHAT_MAX_ATTACHMENT_BYTES", 10 * 1024 * 1024)
AI_CHAT_MAX_TOTAL_ATTACHMENT_BYTES = _int_env("AI_CHAT_MAX_TOTAL_ATTACHMENT_BYTES", 25 * 1024 * 1024)
AI_CHAT_MAX_AUDIO_BYTES = _int_env("AI_CHAT_MAX_AUDIO_BYTES", 15 * 1024 * 1024)
OPENAI_API_KEY = _env("OPENAI_API_KEY")
