from .env import _csv_env, _env, _int_env


API_BASE_URL = _env("API_BASE_URL")
PUBLIC_API_BASE_URL = _env("PUBLIC_API_BASE_URL")
CORS_ALLOWED_ORIGINS = _csv_env(
    "CORS_ALLOWED_ORIGINS",
    "https://api-elixirshop.devsivanschostakov.org",
)

REDIS_URL = _env("REDIS_URL")

IOS_MINIMUM_BUILD = _int_env("IOS_MINIMUM_BUILD", 1)
IOS_LATEST_BUILD = _int_env("IOS_LATEST_BUILD", IOS_MINIMUM_BUILD)
IOS_MINIMUM_JS_BUNDLE_VERSION = _int_env("IOS_MINIMUM_JS_BUNDLE_VERSION", 1)
IOS_LATEST_JS_BUNDLE_VERSION = _int_env("IOS_LATEST_JS_BUNDLE_VERSION", IOS_MINIMUM_JS_BUNDLE_VERSION)
IOS_STORE_URL = _env("IOS_STORE_URL", "")

ANDROID_MINIMUM_VERSION_CODE = _int_env("ANDROID_MINIMUM_VERSION_CODE", 1)
ANDROID_LATEST_VERSION_CODE = _int_env("ANDROID_LATEST_VERSION_CODE", ANDROID_MINIMUM_VERSION_CODE)
ANDROID_MINIMUM_JS_BUNDLE_VERSION = _int_env("ANDROID_MINIMUM_JS_BUNDLE_VERSION", 1)
ANDROID_LATEST_JS_BUNDLE_VERSION = _int_env("ANDROID_LATEST_JS_BUNDLE_VERSION", ANDROID_MINIMUM_JS_BUNDLE_VERSION)
ANDROID_STORE_URL = _env("ANDROID_STORE_URL", "")
