from .env import _env, _float_env, _int_env


APP_INTEGRITY_MODE = (_env("APP_INTEGRITY_MODE", "enforce") or "enforce").strip().lower()
APP_INTEGRITY_VERIFIER_URL = _env("APP_INTEGRITY_VERIFIER_URL")
APP_INTEGRITY_VERIFIER_TIMEOUT_SECONDS = _float_env("APP_INTEGRITY_VERIFIER_TIMEOUT_SECONDS", 5.0)
APP_INTEGRITY_DEV_TOKEN = _env("APP_INTEGRITY_DEV_TOKEN")
APP_INTEGRITY_ANDROID_PACKAGE_NAME = _env("APP_INTEGRITY_ANDROID_PACKAGE_NAME")
APP_INTEGRITY_ANDROID_CLOUD_PROJECT_NUMBER = _env(
    "APP_INTEGRITY_ANDROID_CLOUD_PROJECT_NUMBER",
    _env("EXPO_PUBLIC_PLAY_INTEGRITY_CLOUD_PROJECT_NUMBER"),
)
APP_INTEGRITY_ANDROID_CERT_SHA256_DIGESTS = _env("APP_INTEGRITY_ANDROID_CERT_SHA256_DIGESTS")
APP_INTEGRITY_ANDROID_ALLOWED_DEVICE_VERDICTS = _env(
    "APP_INTEGRITY_ANDROID_ALLOWED_DEVICE_VERDICTS",
    "MEETS_DEVICE_INTEGRITY",
)
APP_INTEGRITY_TOKEN_MAX_AGE_SECONDS = _int_env("APP_INTEGRITY_TOKEN_MAX_AGE_SECONDS", 120)
APP_INTEGRITY_CHALLENGE_TTL_SECONDS = _int_env("APP_INTEGRITY_CHALLENGE_TTL_SECONDS", 120)
APP_INTEGRITY_IOS_TEAM_ID = _env("APP_INTEGRITY_IOS_TEAM_ID")
APP_INTEGRITY_IOS_BUNDLE_ID = _env("APP_INTEGRITY_IOS_BUNDLE_ID")
APP_INTEGRITY_IOS_ALLOWED_ENVIRONMENTS = _env("APP_INTEGRITY_IOS_ALLOWED_ENVIRONMENTS", "production")
