from .env import _int_env


CUSTOMER_EVENT_RETENTION_DAYS = _int_env("CUSTOMER_EVENT_RETENTION_DAYS", 365)
CUSTOMER_EVENT_CLEANUP_INTERVAL_SECONDS = _int_env("CUSTOMER_EVENT_CLEANUP_INTERVAL_SECONDS", 86400)
