from .env import _env, _int_env


SMTP_HOST = _env("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = _int_env("SMTP_PORT", 587)
SMTP_USER = _env("SMTP_USER")
SMTP_PASSWORD = _env("SMTP_PASSWORD")
SMTP_FROM_NAME = _env("SMTP_FROM_NAME", "ElixirPeptide")

EMAIL_VERIFICATION_CODE_TTL_MINUTES = _int_env("EMAIL_VERIFICATION_CODE_TTL_MINUTES", 10)
EMAIL_VERIFICATION_MAX_ATTEMPTS = _int_env("EMAIL_VERIFICATION_MAX_ATTEMPTS", 5)
