from .env import _env, _float_env, _int_env


EXPO_PUSH_API_URL = _env("EXPO_PUSH_API_URL", "https://exp.host/--/api/v2/push/send")
EXPO_PUSH_TIMEOUT_SECONDS = _float_env("EXPO_PUSH_TIMEOUT_SECONDS", 15)

NOTIFICATION_SCAN_INTERVAL_MINUTES = _int_env("NOTIFICATION_SCAN_INTERVAL_MINUTES", 15)
NOTIFICATION_BATCH_SIZE = _int_env("NOTIFICATION_BATCH_SIZE", 200)
NOTIFICATION_RESTOCK_LOW_STOCK_THRESHOLD = _int_env("NOTIFICATION_RESTOCK_LOW_STOCK_THRESHOLD", 10)
NOTIFICATION_INACTIVE_CUSTOMER_AFTER_DAYS = _int_env("NOTIFICATION_INACTIVE_CUSTOMER_AFTER_DAYS", 45)
NOTIFICATION_INACTIVE_CUSTOMER_COOLDOWN_DAYS = _int_env("NOTIFICATION_INACTIVE_CUSTOMER_COOLDOWN_DAYS", 14)
NOTIFICATION_ABANDONED_CART_AFTER_HOURS = _int_env("NOTIFICATION_ABANDONED_CART_AFTER_HOURS", 24)
NOTIFICATION_ABANDONED_CART_COOLDOWN_HOURS = _int_env("NOTIFICATION_ABANDONED_CART_COOLDOWN_HOURS", 24)
NOTIFICATION_REVIEW_REMINDER_AFTER_DAYS = _int_env("NOTIFICATION_REVIEW_REMINDER_AFTER_DAYS", 30)
