from .env import _int_env


AUTH_RATE_LIMIT_WINDOW_SECONDS = _int_env("AUTH_RATE_LIMIT_WINDOW_SECONDS", 60)
AUTH_RATE_LIMIT_MAX_REQUESTS = _int_env("AUTH_RATE_LIMIT_MAX_REQUESTS", 20)
AUTH_VERIFY_RATE_LIMIT_MAX_REQUESTS = _int_env("AUTH_VERIFY_RATE_LIMIT_MAX_REQUESTS", 10)
WEBHOOK_RATE_LIMIT_WINDOW_SECONDS = _int_env("WEBHOOK_RATE_LIMIT_WINDOW_SECONDS", 60)
WEBHOOK_RATE_LIMIT_MAX_REQUESTS = _int_env("WEBHOOK_RATE_LIMIT_MAX_REQUESTS", 120)
