from .env import _bool_env, _env, _int_env


REFRESH_TOKEN_LIFETIME_DAYS = _int_env("REFRESH_TOKEN_LIFETIME_DAYS", 30)
JWT_ACCESS_EXPIRE_MINUTES = _int_env("JWT_ACCESS_EXPIRE_MINUTES", 15)
JWT_ACCESS_SECRET_KEY = _env("JWT_ACCESS_SECRET_KEY")
AUTH_LOGIN_WEBSITE_FIRST_ENABLED = _bool_env("AUTH_LOGIN_WEBSITE_FIRST_ENABLED", False)
AI_CHAT_ACTION_SECRET = _env("AI_CHAT_ACTION_SECRET", JWT_ACCESS_SECRET_KEY)
AI_CHAT_ACTION_TOKEN_TTL_SECONDS = _int_env("AI_CHAT_ACTION_TOKEN_TTL_SECONDS", 3600)
