from .env import _int_env


SUPPORT_MAX_ATTACHMENTS = _int_env("SUPPORT_MAX_ATTACHMENTS", 4)
SUPPORT_MAX_ATTACHMENT_BYTES = _int_env("SUPPORT_MAX_ATTACHMENT_BYTES", 8 * 1024 * 1024)
SUPPORT_MAX_TOTAL_ATTACHMENT_BYTES = _int_env("SUPPORT_MAX_TOTAL_ATTACHMENT_BYTES", 20 * 1024 * 1024)
