from .env import _bool_env, _env, _float_env, _int_env


TELEGRAM_BOT_TOKEN = _env("TELEGRAM_BOT_TOKEN")
TELEGRAM_WEBHOOK_SECRET_TOKEN = _env("TELEGRAM_WEBHOOK_SECRET_TOKEN")
TELEGRAM_AUTH_MAX_AGE_SECONDS = _int_env("TELEGRAM_AUTH_MAX_AGE_SECONDS", 86400)
TELEGRAM_API_BASE_URL = _env("TELEGRAM_API_BASE_URL", "https://api.telegram.org")
TELEGRAM_PROXY_URL = (_env("TELEGRAM_PROXY_URL") or "").strip().strip('"').strip("'") or None
TELEGRAM_POLLING_INTERVAL_SECONDS = _float_env("TELEGRAM_POLLING_INTERVAL_SECONDS", 1.0)
TELEGRAM_POLLING_TIMEOUT_SECONDS = _int_env("TELEGRAM_POLLING_TIMEOUT_SECONDS", 30)
TELEGRAM_COMMUNITY_ENABLED = _bool_env("TELEGRAM_COMMUNITY_ENABLED", False)
TELEGRAM_COMMUNITY_CHAT_ID = _int_env("TELEGRAM_COMMUNITY_CHAT_ID", 0)
TELEGRAM_COMMUNITY_JOIN_URL = (_env("TELEGRAM_COMMUNITY_JOIN_URL") or "").strip() or None
TELEGRAM_BOT_USERNAME = (_env("TELEGRAM_BOT_USERNAME") or "").strip().lstrip("@") or None
TELEGRAM_COMMUNITY_MEMBERSHIP_CACHE_SECONDS = _int_env(
    "TELEGRAM_COMMUNITY_MEMBERSHIP_CACHE_SECONDS",
    300,
)
TELEGRAM_COMMUNITY_PROFILE_CACHE_SECONDS = _int_env(
    "TELEGRAM_COMMUNITY_PROFILE_CACHE_SECONDS",
    86400,
)
TELEGRAM_COMMUNITY_MAX_ATTACHMENTS = _int_env("TELEGRAM_COMMUNITY_MAX_ATTACHMENTS", 6)
TELEGRAM_COMMUNITY_MAX_ATTACHMENT_BYTES = _int_env(
    "TELEGRAM_COMMUNITY_MAX_ATTACHMENT_BYTES",
    10 * 1024 * 1024,
)
TELEGRAM_COMMUNITY_MAX_TOTAL_ATTACHMENT_BYTES = _int_env(
    "TELEGRAM_COMMUNITY_MAX_TOTAL_ATTACHMENT_BYTES",
    25 * 1024 * 1024,
)
TELEGRAM_COMMUNITY_MAX_DOWNLOAD_BYTES = _int_env(
    "TELEGRAM_COMMUNITY_MAX_DOWNLOAD_BYTES",
    20 * 1024 * 1024,
)
TELEGRAM_COMMUNITY_MEDIA_SIGNING_SECRET = (
    _env("TELEGRAM_COMMUNITY_MEDIA_SIGNING_SECRET") or ""
).strip() or None
