from .env import _env, _float_env, _int_env


TELEGRAM_BOT_TOKEN = _env("TELEGRAM_BOT_TOKEN")
TELEGRAM_WEBHOOK_SECRET_TOKEN = _env("TELEGRAM_WEBHOOK_SECRET_TOKEN")
TELEGRAM_AUTH_MAX_AGE_SECONDS = _int_env("TELEGRAM_AUTH_MAX_AGE_SECONDS", 86400)
TELEGRAM_API_BASE_URL = _env("TELEGRAM_API_BASE_URL", "https://api.telegram.org")
TELEGRAM_PROXY_URL = (_env("TELEGRAM_PROXY_URL") or "").strip().strip('"').strip("'") or None
TELEGRAM_POLLING_INTERVAL_SECONDS = _float_env("TELEGRAM_POLLING_INTERVAL_SECONDS", 1.0)
TELEGRAM_POLLING_TIMEOUT_SECONDS = _int_env("TELEGRAM_POLLING_TIMEOUT_SECONDS", 30)
