from pathlib import Path

from .env import _bool_env, _env, _float_env, _int_env
from .paths import WORKING_DIR


TELEGRAM_BOT_TOKEN = _env("TELEGRAM_BOT_TOKEN")
TELEGRAM_WEBHOOK_SECRET_TOKEN = _env("TELEGRAM_WEBHOOK_SECRET_TOKEN")
TELEGRAM_AUTH_MAX_AGE_SECONDS = _int_env("TELEGRAM_AUTH_MAX_AGE_SECONDS", 86400)
TELEGRAM_API_BASE_URL = _env("TELEGRAM_API_BASE_URL", "https://api.telegram.org")
TELEGRAM_PROXY_URL = (_env("TELEGRAM_PROXY_URL") or "").strip().strip('"').strip("'") or None
TELEGRAM_POLLING_INTERVAL_SECONDS = _float_env("TELEGRAM_POLLING_INTERVAL_SECONDS", 1.0)
TELEGRAM_POLLING_TIMEOUT_SECONDS = _int_env("TELEGRAM_POLLING_TIMEOUT_SECONDS", 30)
TELEGRAM_COMMUNITY_ENABLED = _bool_env("TELEGRAM_COMMUNITY_ENABLED", False)
TELEGRAM_COMMUNITY_CHAT_ID = _int_env("TELEGRAM_COMMUNITY_CHAT_ID", 0)
TELEGRAM_COMMUNITY_JOIN_URL = (_env("TELEGRAM_COMMUNITY_JOIN_URL") or "").strip() or None
TELEGRAM_BOT_USERNAME = (_env("TELEGRAM_BOT_USERNAME") or "").strip().lstrip("@") or None
TELEGRAM_COMMUNITY_MEMBERSHIP_CACHE_SECONDS = _int_env(
    "TELEGRAM_COMMUNITY_MEMBERSHIP_CACHE_SECONDS",
    300,
)
TELEGRAM_COMMUNITY_PROFILE_CACHE_SECONDS = _int_env(
    "TELEGRAM_COMMUNITY_PROFILE_CACHE_SECONDS",
    86400,
)
TELEGRAM_COMMUNITY_MAX_ATTACHMENTS = _int_env("TELEGRAM_COMMUNITY_MAX_ATTACHMENTS", 6)
TELEGRAM_COMMUNITY_MAX_ATTACHMENT_BYTES = _int_env(
    "TELEGRAM_COMMUNITY_MAX_ATTACHMENT_BYTES",
    10 * 1024 * 1024,
)
TELEGRAM_COMMUNITY_MAX_TOTAL_ATTACHMENT_BYTES = _int_env(
    "TELEGRAM_COMMUNITY_MAX_TOTAL_ATTACHMENT_BYTES",
    25 * 1024 * 1024,
)
TELEGRAM_COMMUNITY_MAX_DOWNLOAD_BYTES = _int_env(
    "TELEGRAM_COMMUNITY_MAX_DOWNLOAD_BYTES",
    20 * 1024 * 1024,
)
TELEGRAM_COMMUNITY_MEDIA_SIGNING_SECRET = (
    _env("TELEGRAM_COMMUNITY_MEDIA_SIGNING_SECRET") or ""
).strip() or None

# This user-authorized MTProto client is used only for authoritative forum
# topic metadata. Bot API polling remains the real-time message transport.
TELEGRAM_USERBOT_ENABLED = _bool_env("TELEGRAM_USERBOT_ENABLED", False)
TELEGRAM_USERBOT_API_ID = _int_env("TELEGRAM_USERBOT_API_ID", 0)
TELEGRAM_USERBOT_API_HASH = (_env("TELEGRAM_USERBOT_API_HASH") or "").strip() or None
TELEGRAM_USERBOT_PHONE = (_env("TELEGRAM_USERBOT_PHONE") or "").strip() or None
TELEGRAM_USERBOT_SESSION_PATH = Path(
    _env(
        "TELEGRAM_USERBOT_SESSION_PATH",
        str(WORKING_DIR / ".secrets" / "telegram-userbot" / "community"),
    )
    or str(WORKING_DIR / ".secrets" / "telegram-userbot" / "community")
)
TELEGRAM_USERBOT_PROXY_URL = (
    _env("TELEGRAM_USERBOT_PROXY_URL", TELEGRAM_PROXY_URL or "") or ""
).strip() or None
TELEGRAM_USERBOT_TOPIC_SYNC_INTERVAL_SECONDS = _int_env(
    "TELEGRAM_USERBOT_TOPIC_SYNC_INTERVAL_SECONDS",
    60,
)
TELEGRAM_USERBOT_HISTORY_SYNC_INTERVAL_SECONDS = _int_env(
    "TELEGRAM_USERBOT_HISTORY_SYNC_INTERVAL_SECONDS",
    60,
)
TELEGRAM_USERBOT_ADMIN_LOG_SYNC_INTERVAL_SECONDS = _float_env(
    "TELEGRAM_USERBOT_ADMIN_LOG_SYNC_INTERVAL_SECONDS",
    3.0,
)
TELEGRAM_USERBOT_FULL_HISTORY_RECONCILE_SECONDS = _int_env(
    "TELEGRAM_USERBOT_FULL_HISTORY_RECONCILE_SECONDS",
    86400,
)
