import { Platform, StyleSheet } from "react-native"

import { colors } from "@/theme/colors"
import { spacing } from "@/theme/spacing"

export const paymentScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.surface,
    },
    scrollView: {
        flex: 1,
        backgroundColor: colors.surface,
    },
    content: {
        backgroundColor: colors.pageBackground,
        paddingVertical: spacing.md,
        paddingBottom: spacing.xl,
        gap: spacing.md,
    },
    contentQROnly: {
        paddingTop: 0,
    },
    card: {
        backgroundColor: colors.surface,
        borderRadius: 28,
        paddingHorizontal: spacing.lg,
        paddingVertical: spacing.lg,
        gap: spacing.md,
    },
    visualCard: {
        paddingHorizontal: 0,
        paddingTop: spacing.md,
        paddingBottom: spacing.sm,
        minHeight: 320,
    },
    visualCardQROnly: {
        paddingTop: 0,
        paddingBottom: 0,
        minHeight: 0,
    },
    sectionHeader: {
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "space-between",
        gap: spacing.sm,
    },
    eyebrow: {
        color: colors.primary,
        fontSize: 11,
        lineHeight: 14,
        fontWeight: "700",
        letterSpacing: 0.8,
        textTransform: "uppercase",
    },
    title: {
        fontSize: 26,
        lineHeight: 32,
        fontWeight: "800",
        color: colors.text,
    },
    sectionTitle: {
        fontSize: 22,
        lineHeight: 28,
        fontWeight: "800",
        color: colors.text,
    },
    subtitle: {
        fontSize: 15,
        lineHeight: 22,
        color: colors.mutedText,
    },
    headerTitleButton: {
        alignItems: "center",
        justifyContent: "center",
        minHeight: 34,
        paddingHorizontal: 6,
        width: "100%",
    },
    headerTitleButtonPressed: {
        opacity: 0.62,
    },
    headerTitleText: {
        color: colors.text,
        fontSize: 18,
        fontWeight: "700",
        textAlign: "center",
        width: "100%",
    },
    summaryRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        gap: spacing.md,
        alignItems: "flex-start",
    },
    summaryLabel: {
        flex: 1,
        color: colors.mutedText,
        fontSize: 14,
        lineHeight: 20,
    },
    summaryValue: {
        flex: 1,
        color: colors.text,
        fontSize: 14,
        lineHeight: 20,
        textAlign: "right",
        fontWeight: "700",
    },
    methods: {
        gap: spacing.sm,
    },
    methodCard: {
        borderRadius: 22,
        borderWidth: 1,
        borderColor: "rgba(17,17,17,0.08)",
        padding: spacing.md,
        gap: 6,
        backgroundColor: colors.surfaceElevated,
    },
    methodCardActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primaryMuted,
    },
    methodCardDangerActive: {
        borderColor: "#F04438",
        backgroundColor: "#FEF3F2",
    },
    methodCardPressed: {
        opacity: 0.88,
    },
    methodTitle: {
        color: colors.text,
        fontSize: 16,
        lineHeight: 20,
        fontWeight: "700",
    },
    methodTitleDanger: {
        color: "#B42318",
    },
    methodDescription: {
        color: colors.mutedText,
        fontSize: 14,
        lineHeight: 20,
    },
    primaryButton: {
        minHeight: 54,
        borderRadius: 18,
        backgroundColor: colors.text,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: spacing.lg,
    },
    primaryButtonPressed: {
        opacity: 0.88,
    },
    primaryButtonDisabled: {
        backgroundColor: "#CDD3DD",
    },
    primaryButtonText: {
        color: colors.surface,
        fontSize: 16,
        lineHeight: 20,
        fontWeight: "800",
    },
    secondaryButton: {
        minHeight: 48,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "rgba(17,17,17,0.08)",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: spacing.lg,
        backgroundColor: colors.surfaceElevated,
    },
    secondaryButtonPressed: {
        opacity: 0.82,
    },
    secondaryButtonText: {
        color: colors.text,
        fontSize: 15,
        lineHeight: 20,
        fontWeight: "700",
    },
    visualWrap: {
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: spacing.lg,
        minHeight: 320,
    },
    visualWrapQROnly: {
        justifyContent: "flex-start",
        paddingTop: 0,
        minHeight: 0,
    },
    qrFrame: {
        width: "100%",
        alignSelf: "center",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: colors.surface,
        borderRadius: 32,
        paddingHorizontal: spacing.md,
    },
    qrFrameQROnly: {
        borderTopLeftRadius: 0,
        borderTopRightRadius: 0,
    },
    qrFramePressed: {
        opacity: 0.9,
    },
    visualPlaceholder: {
        width: "84%",
        maxWidth: 360,
        aspectRatio: 1,
        alignSelf: "center",
        borderRadius: 24,
        backgroundColor: colors.surface,
    },
    qrImage: {
        width: "84%",
        maxWidth: 360,
        aspectRatio: 1,
        alignSelf: "center",
        borderRadius: 24,
        backgroundColor: colors.surface,
    },
    qrPlaceholder: {
        width: "100%",
        minHeight: 240,
        borderRadius: 20,
        backgroundColor: colors.pageBackground,
        alignItems: "center",
        justifyContent: "center",
        padding: spacing.md,
        gap: spacing.sm,
    },
    qrPlaceholderText: {
        textAlign: "center",
        color: colors.mutedText,
        fontSize: 14,
        lineHeight: 20,
    },
    centerState: {
        alignItems: "center",
        justifyContent: "center",
        gap: spacing.sm,
        paddingVertical: spacing.lg,
    },
    stateText: {
        color: colors.mutedText,
        fontSize: 15,
        lineHeight: 22,
        textAlign: "center",
    },
    failureVisualBody: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        gap: spacing.sm,
        paddingVertical: spacing.lg,
    },
    activityRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: spacing.sm,
    },
    errorText: {
        color: "#B42318",
        fontSize: 14,
        lineHeight: 20,
    },
    successAnimation: {
        width: 150,
        height: 150,
    },
    successVisualWrap: {
        gap: spacing.md,
        overflow: "hidden",
        paddingHorizontal: spacing.lg,
    },
    confettiLayer: {
        ...StyleSheet.absoluteFillObject,
        overflow: "hidden",
        zIndex: 2,
    },
    confettiPiece: {
        position: "absolute",
        borderRadius: 3,
    },
    successCopy: {
        alignItems: "center",
        gap: spacing.sm,
        width: "100%",
    },
    successBadge: {
        alignSelf: "center",
        backgroundColor: "#EAF8F2",
        borderRadius: 999,
        color: "#047857",
        fontSize: 12,
        fontWeight: "800",
        lineHeight: 16,
        paddingHorizontal: spacing.md,
        paddingVertical: 6,
        textTransform: "uppercase",
    },
    successTitle: {
        color: colors.text,
        fontSize: 26,
        fontWeight: "800",
        lineHeight: 32,
        textAlign: "center",
    },
    successMessage: {
        color: colors.mutedText,
        fontSize: 15,
        lineHeight: 22,
        maxWidth: 360,
        textAlign: "center",
    },
    successOrderBox: {
        alignItems: "center",
        backgroundColor: colors.surface,
        borderRadius: 18,
        marginTop: spacing.xs,
        paddingHorizontal: spacing.lg,
        paddingVertical: spacing.sm,
        width: "100%",
    },
    successOrderBoxPressed: {
        opacity: 0.76,
    },
    successOrderLabel: {
        color: colors.mutedText,
        fontSize: 12,
        fontWeight: "700",
        lineHeight: 16,
        textTransform: "uppercase",
    },
    successOrderValue: {
        color: colors.text,
        fontSize: 22,
        fontWeight: "800",
        lineHeight: 28,
        textAlign: "center",
    },
    infoPanel: {
        backgroundColor: colors.surfaceElevated,
        borderRadius: 20,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.md,
        gap: spacing.sm,
    },
    infoLabel: {
        color: colors.mutedText,
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "700",
        textTransform: "uppercase",
    },
    infoBlock: {
        gap: 4,
    },
    infoPrimary: {
        color: colors.text,
        fontSize: 16,
        lineHeight: 22,
        fontWeight: "700",
    },
    infoSecondary: {
        color: colors.mutedText,
        fontSize: 14,
        lineHeight: 20,
    },
    compositionList: {
        gap: spacing.sm,
    },
    compositionRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: spacing.sm,
    },
    compositionImage: {
        width: 60,
        height: 60,
        borderRadius: 16,
        backgroundColor: colors.surfaceMuted,
    },
    compositionBody: {
        flex: 1,
        gap: 2,
        minWidth: 0,
    },
    compositionTitle: {
        color: colors.text,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "700",
    },
    compositionSubtitle: {
        color: colors.mutedText,
        fontSize: 13,
        lineHeight: 18,
    },
    compositionMeta: {
        color: colors.mutedText,
        fontSize: 12,
        lineHeight: 16,
    },
    compositionPrice: {
        color: colors.text,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "700",
        textAlign: "right",
    },
    footerActionStack: {
        gap: spacing.sm,
    },
    summaryCard: {
        gap: spacing.md,
    },
    summarySectionCard: {
        backgroundColor: colors.surface,
        borderRadius: spacing.lg,
        gap: spacing.xs,
        paddingHorizontal: spacing.lg,
        paddingTop: spacing.sm,
        paddingBottom: spacing.md,
        ...Platform.select({
            web: {
                boxShadow: "0 8px 16px rgba(0, 0, 0, 0.04)",
            },
            default: {
                shadowColor: "#000000",
                shadowOffset: { width: 0, height: 8 },
                shadowOpacity: 0.04,
                shadowRadius: 16,
            },
        }),
        width: "100%",
    },
    sectionToggle: {
        alignItems: "center",
        flexDirection: "row",
        gap: spacing.md,
        justifyContent: "space-between",
        minHeight: 36,
    },
    sectionTogglePressed: {
        opacity: 0.82,
    },
    sectionToggleTitle: {
        color: colors.text,
        flex: 1,
        fontSize: 17,
        lineHeight: 22,
        fontWeight: "800",
    },
    sectionToggleArrow: {
        color: colors.mutedText,
        fontSize: 18,
        lineHeight: 18,
        transform: [{ rotate: "-90deg" }],
    },
    sectionToggleArrowExpanded: {
        transform: [{ rotate: "0deg" }],
    },
    sectionBody: {
        gap: spacing.sm,
        paddingTop: spacing.sm,
    },
    footerInfoCard: {
        backgroundColor: "transparent",
        borderRadius: 0,
        paddingHorizontal: 0,
        paddingVertical: spacing.xs,
        gap: spacing.md,
    },
    footerInfoSection: {
        gap: spacing.xs,
    },
    footerInfoSectionSlim: {
        gap: 6,
    },
    footerTopRow: {
        gap: spacing.md,
    },
    footerInfoColumn: {
        gap: spacing.sm,
        minWidth: 0,
    },
    footerPriceColumn: {
        gap: 6,
    },
    footerPriceRow: {
        alignItems: "center",
        flexDirection: "row",
        gap: spacing.sm,
        justifyContent: "space-between",
    },
    footerPriceRowTotal: {
        marginTop: 2,
    },
    footerPriceLabel: {
        color: colors.mutedText,
        fontSize: 15,
        lineHeight: 20,
    },
    footerPriceValue: {
        color: colors.text,
        fontSize: 15,
        lineHeight: 20,
        fontWeight: "700",
        textAlign: "right",
    },
    footerPriceLabelStrong: {
        color: colors.text,
        fontSize: 16,
        lineHeight: 22,
        fontWeight: "700",
    },
    footerPriceValueStrong: {
        color: colors.text,
        fontSize: 18,
        lineHeight: 24,
        fontWeight: "800",
        textAlign: "right",
    },
    footerDivider: {
        backgroundColor: "rgba(17, 24, 39, 0.08)",
        height: 1,
    },
    footerMetaRow: {
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "space-between",
        gap: spacing.sm,
    },
    footerMetaTotal: {
        color: colors.text,
        fontSize: 15,
        lineHeight: 20,
        fontWeight: "800",
    },
    footerPrimaryLine: {
        color: colors.text,
        fontSize: 18,
        lineHeight: 24,
        fontWeight: "700",
    },
    footerSecondaryLine: {
        color: colors.mutedText,
        fontSize: 16,
        lineHeight: 22,
    },
    footerCompositionList: {
        gap: spacing.sm,
    },
    footerCompositionSection: {
        gap: spacing.md,
    },
    footerCompositionRow: {
        alignItems: "center",
        flexDirection: "row",
        gap: spacing.sm,
    },
    footerCompositionImage: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: colors.surfaceMuted,
    },
    footerCompositionBody: {
        flex: 1,
        gap: 2,
        minWidth: 0,
    },
    footerCompositionTitle: {
        color: colors.text,
        fontSize: 16,
        lineHeight: 22,
        fontWeight: "700",
    },
    footerCompositionMeta: {
        color: colors.mutedText,
        fontSize: 15,
        lineHeight: 20,
    },
    footerCompositionPrice: {
        color: colors.text,
        fontSize: 16,
        lineHeight: 22,
        fontWeight: "700",
        textAlign: "right",
    },
    footerTotalRow: {
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: spacing.xs,
        gap: spacing.md,
    },
    footerTotalLabel: {
        color: colors.mutedText,
        fontSize: 14,
        lineHeight: 20,
    },
    footerTotalValue: {
        color: colors.text,
        fontSize: 15,
        lineHeight: 20,
        fontWeight: "800",
    },
    footerCtaContent: {
        alignItems: "center",
        flexDirection: "row",
        gap: spacing.sm,
        justifyContent: "center",
    },
    actionsRow: {
        flexDirection: "row",
        gap: spacing.sm,
        marginHorizontal: spacing.md,
    },
    flexButton: {
        flex: 1,
    },
    loadingOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(243, 245, 248, 0.72)",
        alignItems: "center",
        justifyContent: "center",
        padding: spacing.lg,
    },
    loadingOverlayCard: {
        minWidth: 180,
        borderRadius: 20,
        backgroundColor: colors.surfaceOverlay,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: spacing.lg,
        paddingVertical: spacing.md,
        gap: spacing.sm,
    },
    loadingOverlayText: {
        color: colors.text,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "700",
        textAlign: "center",
    },
})
