from datetime import datetime
from os import getenv
from pathlib import Path
from zoneinfo import ZoneInfo
from dotenv import load_dotenv

load_dotenv()

POSTGRES_DB = getenv("POSTGRES_DB")
POSTGRES_USER = getenv("POSTGRES_USER")
POSTGRES_PORT = int(getenv("POSTGRES_PORT"))
POSTGRES_HOST = getenv("POSTGRES_HOST")
POSTGRES_PASSWORD = getenv("POSTGRES_PASSWORD")

GEOSUGGEST_API_KEY = getenv("GEOSUGGEST_API_KEY")
GEOSUGGEST_API_URL = getenv("GEOSUGGEST_API_URL")
GEOCODE_API_URL = getenv("GEOCODE_API_URL")
GEOCODE_API_KEY = getenv("GEOCODE_API_KEY")

YANDEX_DELIVERY_BASE_URL = getenv("YANDEX_DELIVERY_BASE_URL")
YANDEX_DELIVERY_TOKEN = getenv("YANDEX_DELIVERY_TOKEN")
YANDEX_DELIVERY_WAREHOUSE_ID = getenv("YANDEX_DELIVERY_WAREHOUSE_ID")

ASYNC_DB_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}/{POSTGRES_DB}"
API_BASE_URL = getenv("API_BASE_URL")
WEBSITE_IDENTITY_ENDPOINT = getenv("WEBSITE_IDENTITY_ENDPOINT")
WEBSITE_IDENTITY_TIMEOUT_SECONDS = int(getenv("WEBSITE_IDENTITY_TIMEOUT_SECONDS", 15))
BITRIX_SYNC_API_ENDPOINT = getenv("BITRIX_SYNC_API_ENDPOINT")
BITRIX_SYNC_API_APP_KEY = getenv("BITRIX_SYNC_API_APP_KEY")
BITRIX_SYNC_API_APP_SECRET = getenv("BITRIX_SYNC_API_APP_SECRET")
BITRIX_SYNC_API_TIMEOUT_SECONDS = int(getenv("BITRIX_SYNC_API_TIMEOUT_SECONDS", 30))

WORKING_DIR = Path(__file__).parent
LOGS_DIR = WORKING_DIR / "logs"
MEDIA_DIR = WORKING_DIR / "media"
PRODUCTS_MEDIA_DIR = MEDIA_DIR / "products"
AVATARS_MEDIA_DIR = MEDIA_DIR / "avatars"
TEMP_MEDIA_DIR = MEDIA_DIR / "temp"

CDEK_API_URL = getenv("CDEK_API_URL")
CDEK_ACCOUNT = getenv("CDEK_ACCOUNT")
CDEK_SECURE_PASSWORD = getenv("CDEK_SECURE_PASSWORD")

LOGS_DIR.mkdir(parents=True, exist_ok=True)
MEDIA_DIR.mkdir(parents=True, exist_ok=True)
PRODUCTS_MEDIA_DIR.mkdir(parents=True, exist_ok=True)
AVATARS_MEDIA_DIR.mkdir(parents=True, exist_ok=True)

UFA_TZ = ZoneInfo("Asia/Yekaterinburg")


def ufa_now() -> datetime:
    return datetime.now(UFA_TZ)


REFRESH_TOKEN_LIFETIME_DAYS = int(getenv("REFRESH_TOKEN_LIFETIME_DAYS", 30))
JWT_ACCESS_EXPIRE_MINUTES = int(getenv("JWT_ACCESS_EXPIRE_MINUTES", 15))
JWT_ACCESS_SECRET_KEY = getenv("JWT_ACCESS_SECRET_KEY")
