from datetime import datetime
from os import getenv
from pathlib import Path
from zoneinfo import ZoneInfo
from dotenv import load_dotenv

load_dotenv()

POSTGRES_DB = getenv("POSTGRES_DB")
POSTGRES_USER = getenv("POSTGRES_USER")
POSTGRES_PORT = int(getenv("POSTGRES_PORT"))
POSTGRES_HOST = getenv("POSTGRES_HOST")
POSTGRES_PASSWORD = getenv("POSTGRES_PASSWORD")

GEOSUGGEST_API_KEY = getenv("GEOSUGGEST_API_KEY")
GEOSUGGEST_API_URL = getenv("GEOSUGGEST_API_URL")
GEOCODE_API_URL = getenv("GEOCODE_API_URL")
GEOCODE_API_KEY = getenv("GEOCODE_API_KEY")

YANDEX_DELIVERY_BASE_URL = getenv("YANDEX_DELIVERY_BASE_URL")
YANDEX_DELIVERY_TOKEN = getenv("YANDEX_DELIVERY_TOKEN")
YANDEX_DELIVERY_WAREHOUSE_ID = getenv("YANDEX_DELIVERY_WAREHOUSE_ID")

ASYNC_DB_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}/{POSTGRES_DB}"
API_BASE_URL = getenv("API_BASE_URL")
WEBSITE_IDENTITY_ENDPOINT = getenv("WEBSITE_IDENTITY_ENDPOINT")
WEBSITE_IDENTITY_TIMEOUT_SECONDS = int(getenv("WEBSITE_IDENTITY_TIMEOUT_SECONDS", 15))
BITRIX_SYNC_API_ENDPOINT = getenv("BITRIX_SYNC_API_ENDPOINT")
BITRIX_SYNC_API_APP_KEY = getenv("BITRIX_SYNC_API_APP_KEY")
BITRIX_SYNC_API_APP_SECRET = getenv("BITRIX_SYNC_API_APP_SECRET")
BITRIX_SYNC_API_TIMEOUT_SECONDS = int(getenv("BITRIX_SYNC_API_TIMEOUT_SECONDS", 30))
APP_PAYMENT_RETURN_BASE_URL = getenv("APP_PAYMENT_RETURN_BASE_URL")
EXPO_PUSH_API_URL = getenv("EXPO_PUSH_API_URL", "https://exp.host/--/api/v2/push/send")
EXPO_PUSH_TIMEOUT_SECONDS = float(getenv("EXPO_PUSH_TIMEOUT_SECONDS", 15))

WORKING_DIR = Path(__file__).parent
LOGS_DIR = WORKING_DIR / "logs"
MEDIA_DIR = WORKING_DIR / "media"
PRODUCTS_MEDIA_DIR = MEDIA_DIR / "products"
AVATARS_MEDIA_DIR = MEDIA_DIR / "avatars"
ORDERS_MEDIA_DIR = MEDIA_DIR / "orders"
TEMP_MEDIA_DIR = MEDIA_DIR / "temp"

CDEK_API_URL = getenv("CDEK_API_URL")
CDEK_ACCOUNT = getenv("CDEK_ACCOUNT")
CDEK_SECURE_PASSWORD = getenv("CDEK_SECURE_PASSWORD")
CDEK_SENDER_CITY_CODE = int(getenv("CDEK_SENDER_CITY_CODE", "256"))
CDEK_SENDER_CITY = getenv("CDEK_SENDER_CITY", "Уфа")
CDEK_SENDER_POSTAL_CODE = getenv("CDEK_SENDER_POSTAL_CODE", "450078")
CDEK_SENDER_ADDRESS = getenv("CDEK_SENDER_ADDRESS", "ул. Революционная, 98/1 блок А")
CDEK_SENDER_NAME = getenv("CDEK_SENDER_NAME", "Elixir Peptide")
CDEK_SENDER_PHONE = getenv("CDEK_SENDER_PHONE", "+79999999999")

AMOCRM_BASE_DOMAIN = getenv("AMOCRM_BASE_DOMAIN")
AMOCRM_CLIENT_ID = getenv("AMOCRM_CLIENT_ID")
AMOCRM_CLIENT_SECRET = getenv("AMOCRM_CLIENT_SECRET")
AMOCRM_ACCESS_TOKEN = getenv("AMOCRM_ACCESS_TOKEN")
AMOCRM_REFRESH_TOKEN = getenv("AMOCRM_REFRESH_TOKEN")
AMOCRM_REDIRECT_URI = getenv("AMOCRM_REDIRECT_URI")
AMOCRM_AUTH_CODE = getenv("AMOCRM_AUTH_CODE")
AMOCRM_LOGIN_EMAIL = getenv("AMOCRM_LOGIN_EMAIL")
AMOCRM_LOGIN_PASSWORD = getenv("AMOCRM_LOGIN_PASSWORD")
AMOCRM_ACCOUNT_ID = getenv("AMOCRM_ACCOUNT_ID", "19843447")
AMOCRM_PLAYWRIGHT_HEADLESS = (getenv("AMOCRM_PLAYWRIGHT_HEADLESS", "false") or "false").strip().lower() in {"1", "true", "yes", "on"}

INTELLECTMONEY_API_BASE = getenv("INTELLECTMONEY_API_BASE", "https://merchant.intellectmoney.ru")
INTELLECTMONEY_BEARER_TOKEN = getenv("INTELLECTMONEY_BEARER_TOKEN")
INTELLECTMONEY_SECRET_KEY = getenv("INTELLECTMONEY_SECRET_KEY")
INTELLECTMONEY_SIGN_SECRET_KEY = getenv("INTELLECTMONEY_SIGN_SECRET_KEY")
INTELLECTMONEY_SHOP_ID = getenv("INTELLECTMONEY_SHOP_ID")

LOGS_DIR.mkdir(parents=True, exist_ok=True)
MEDIA_DIR.mkdir(parents=True, exist_ok=True)
PRODUCTS_MEDIA_DIR.mkdir(parents=True, exist_ok=True)
AVATARS_MEDIA_DIR.mkdir(parents=True, exist_ok=True)
ORDERS_MEDIA_DIR.mkdir(parents=True, exist_ok=True)

UFA_TZ = ZoneInfo("Asia/Yekaterinburg")


def ufa_now() -> datetime:
    return datetime.now(UFA_TZ)


REFRESH_TOKEN_LIFETIME_DAYS = int(getenv("REFRESH_TOKEN_LIFETIME_DAYS", 30))
JWT_ACCESS_EXPIRE_MINUTES = int(getenv("JWT_ACCESS_EXPIRE_MINUTES", 15))
JWT_ACCESS_SECRET_KEY = getenv("JWT_ACCESS_SECRET_KEY")
