export const CDEK_PICKUP_MARKER_LABEL = "CDEK pickup point"
export const CDEK_PICKUP_MARKER_TEXT = "CDEK"
export const CDEK_PICKUP_MARKER_OUTER_SIZE = 34
export const CDEK_PICKUP_MARKER_INNER_SIZE = 28
export const CDEK_PICKUP_MARKER_OUTER_COLOR = "#00A0E3"
export const CDEK_PICKUP_MARKER_INNER_COLOR = "#10B65A"
export const CDEK_PICKUP_MARKER_INNER_BORDER_COLOR = "#FFFFFF"
export const CDEK_PICKUP_MARKER_TEXT_COLOR = "#FFFFFF"
export const CDEK_PICKUP_MARKER_SHADOW = "0 3px 12px rgba(0, 0, 0, 0.22)"
export const CDEK_PICKUP_MARKER_SCALE = 1.25

export const YANDEX_PICKUP_MARKER_LABEL = "Yandex pickup point"
export const YANDEX_PICKUP_MARKER_TEXT = "YA"
export const YANDEX_PICKUP_MARKER_INNER_COLOR = "#FF5A1F"
