export const FULL_SWIPE_REMOVE_TRIGGER = 148

export const DELIVERY_COUNTRY_NAMES = {
    AE: "ОАЭ",
    AM: "Армения",
    AZ: "Азербайджан",
    BD: "Бангладеш",
    BY: "Беларусь",
    CN: "Китай",
    GE: "Грузия",
    ID: "Индонезия",
    IL: "Израиль",
    IN: "Индия",
    JP: "Япония",
    KG: "Киргизия",
    KZ: "Казахстан",
    MD: "Молдова",
    MN: "Монголия",
    RS: "Сербия",
    RU: "Россия",
    TH: "Таиланд",
    US: "США",
    UZ: "Узбекистан",
    VN: "Вьетнам",
} as const
