from datetime import timedelta

HOME_RECOMMENDATION_LIMIT = 8
DEFAULT_RECOMMENDATION_LIMIT = 6
HOME_CATEGORY_LIMIT = 3

VIEW_DEDUPE_WINDOW = timedelta(minutes=30)
RECENT_PURCHASE_WINDOW = timedelta(days=30)

PURCHASE_SIGNAL_WEIGHT = 12
FAVORITE_SIGNAL_WEIGHT = 8
CART_SIGNAL_WEIGHT = 6
CATEGORY_VIEW_SIGNAL_WEIGHT = 4
VIEW_SIGNAL_WEIGHT = 2
CATEGORY_OVERLAP_WEIGHT = 1

