USERNAME_MAX_LENGTH = 16
EMAIL_MAX_LENGTH = 100
DELIVERY_LABEL_MAX_LENGTH = 100
PERSON_NAME_MAX_LENGTH = 100
PHONE_NUMBER_MAX_LENGTH = 20
PASSWORD_HASH_MAX_LENGTH = 255
DELIVERY_ADDRESS_MAX_LENGTH = 255
DELIVERY_POINT_MAX_LENGTH = 255
DELIVERY_COMMENT_MAX_LENGTH = 255

PRODUCT_SKU_MAX_LENGTH = 64
PRODUCT_NAME_MAX_LENGTH = 200
PRODUCT_DESCRIPTION_MAX_LENGTH = 5000
PRODUCT_USAGE_MAX_LENGTH = 2000
PRODUCT_EXPIRATION_MAX_LENGTH = 1000
VARIANT_SKU_MAX_LENGTH = 64
VARIANT_NAME_MAX_LENGTH = 200
PRODUCT_CATEGORY_NAME_MAX_LENGTH = 200
PRODUCT_CATEGORY_DESCRIPTION_MAX_LENGTH = 5000

REFRESH_TOKEN_HASH_MAX_LENGTH = 255
USER_AGENT_MAX_LENGTH = 512
IP_ADDRESS_MAX_LENGTH = 45

WEBSITE_LOGIN_MAX_LENGTH = 120
WEBSITE_EMAIL_MAX_LENGTH = 190
WEBSITE_PHONE_MAX_LENGTH = 80
WEBSITE_CITY_MAX_LENGTH = 120
ARTICLE_NAME_MAX_LENGTH = 255

BUSINESS_NAME_MAX_LENGTH = 255
PROMO_CODE_MAX_LENGTH = 120
CURRENCY_CODE_MAX_LENGTH = 8
EXTERNAL_ID_MAX_LENGTH = 128
STATUS_MAX_LENGTH = 32
SOURCE_KIND_MAX_LENGTH = 48
LEDGER_NOTE_MAX_LENGTH = 500
