EMAIL_MAX_LENGTH = 100
DELIVERY_LABEL_MAX_LENGTH = 100
PERSON_NAME_MAX_LENGTH = 100
PHONE_NUMBER_MAX_LENGTH = 20
PASSWORD_HASH_MAX_LENGTH = 255
TELEGRAM_USERNAME_MAX_LENGTH = 64
DELIVERY_ADDRESS_MAX_LENGTH = 255
DELIVERY_POINT_MAX_LENGTH = 255
DELIVERY_COMMENT_MAX_LENGTH = 255
DELIVERY_CITY_MAX_LENGTH = 120
DELIVERY_POSTAL_CODE_MAX_LENGTH = 32

PRODUCT_SKU_MAX_LENGTH = 64
PRODUCT_NAME_MAX_LENGTH = 200
PRODUCT_DESCRIPTION_MAX_LENGTH = 5000
PRODUCT_USAGE_MAX_LENGTH = 2000
PRODUCT_EXPIRATION_MAX_LENGTH = 1000
VARIANT_SKU_MAX_LENGTH = 64
VARIANT_NAME_MAX_LENGTH = 200
PRODUCT_CATEGORY_NAME_MAX_LENGTH = 200
PRODUCT_CATEGORY_DESCRIPTION_MAX_LENGTH = 5000
BANNER_IMAGE_PATH_MAX_LENGTH = 1024
BANNER_LINK_MAX_LENGTH = 2048

REFRESH_TOKEN_HASH_MAX_LENGTH = 255
USER_AGENT_MAX_LENGTH = 512
IP_ADDRESS_MAX_LENGTH = 45

WEBSITE_LOGIN_MAX_LENGTH = 120
WEBSITE_EMAIL_MAX_LENGTH = 190
WEBSITE_PHONE_MAX_LENGTH = 80
WEBSITE_CITY_MAX_LENGTH = 120
ARTICLE_NAME_MAX_LENGTH = 255
REQUISITE_TITLE_MAX_LENGTH = 255

BUSINESS_NAME_MAX_LENGTH = 255
PROMO_CODE_MAX_LENGTH = 120
CURRENCY_CODE_MAX_LENGTH = 8
EXTERNAL_ID_MAX_LENGTH = 128
STATUS_MAX_LENGTH = 32
ROUTE_PATH_MAX_LENGTH = 512
SOURCE_KIND_MAX_LENGTH = 48
LEDGER_NOTE_MAX_LENGTH = 500
ORDER_DRAFT_NAME_MAX_LENGTH = 100
ORDER_DRAFT_COMMENT_MAX_LENGTH = 500
ORDER_CODE_MAX_LENGTH = 24
PAYMENT_METHOD_MAX_LENGTH = 32
PAYMENT_PROVIDER_MAX_LENGTH = 64
PAYMENT_STATUS_MAX_LENGTH = 32
ORDER_DELIVERY_STRING_MAX_LENGTH = 500

REVIEW_MAXIMUM_LENGTH = 1000
