from typing import Literal

type CountryCode = Literal[
    "RU",
    "BY",
    "KZ",
    "AZ",
    "MD",
    "AM",
    "UZ",
    "KG",
    "GE",
    "MN",
    "CN",
    "JP",
    "RS",
    "IL",
    "AE",
    "IN",
    "BD",
    "VN",
    "TH",
    "ID",
    "US",
]

COUNTRY_NAMES: dict[CountryCode, str] = {
    "RU": "Россия",
    "BY": "Беларусь",
    "KZ": "Казахстан",
    "AZ": "Азербайджан",
    "MD": "Молдова",
    "AM": "Армения",
    "UZ": "Узбекистан",
    "KG": "Кыргызстан",
    "GE": "Грузия",
    "MN": "Монголия",
    "CN": "Китай",
    "JP": "Япония",
    "RS": "Сербия",
    "IL": "Израиль",
    "AE": "ОАЭ",
    "IN": "Индия",
    "BD": "Бангладеш",
    "VN": "Вьетнам",
    "TH": "Таиланд",
    "ID": "Индонезия",
    "US": "США",
}
