import { StyleSheet } from "react-native"

import type { ThemePalette } from "@/theme/colors"
import { spacing } from "@/theme/spacing"

export const createProfileDiscountsScreenStyles = (colors: ThemePalette) => StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: colors.surface,
    },
    container: {
        flex: 1,
        backgroundColor: colors.pageBackground,
    },
    content: {
        paddingHorizontal: spacing.md,
        paddingTop: spacing.sm,
        paddingBottom: spacing.lg,
        gap: spacing.md,
        backgroundColor: colors.pageBackground,
    },
    summaryCard: {
        position: "relative",
        minHeight: 190,
        overflow: "hidden",
        borderRadius: 28,
        padding: spacing.lg,
        justifyContent: "space-between",
    },
    summaryGlow: {
        position: "absolute",
        width: 220,
        height: 220,
        right: -96,
        top: -112,
        borderRadius: 999,
        backgroundColor: "rgba(255,255,255,0.12)",
    },
    summaryEyebrow: {
        color: "rgba(255,255,255,0.72)",
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "800",
        letterSpacing: 0.8,
        textTransform: "uppercase",
    },
    summaryValueRow: {
        flexDirection: "row",
        alignItems: "flex-end",
        gap: spacing.md,
        marginTop: spacing.xs,
    },
    summaryValue: {
        color: "#FFFFFF",
        fontSize: 52,
        lineHeight: 58,
        fontWeight: "900",
        letterSpacing: -1.8,
    },
    summaryValueLabel: {
        flex: 1,
        color: "rgba(255,255,255,0.88)",
        fontSize: 15,
        lineHeight: 21,
        fontWeight: "700",
        paddingBottom: spacing.sm,
    },
    summaryMeta: {
        marginTop: spacing.md,
        minHeight: 46,
        borderRadius: 15,
        paddingHorizontal: spacing.md,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: spacing.md,
        backgroundColor: "rgba(255,255,255,0.12)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.14)",
    },
    summaryMetaLabel: {
        flex: 1,
        color: "rgba(255,255,255,0.68)",
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "600",
    },
    summaryMetaValue: {
        color: "#FFFFFF",
        fontSize: 15,
        lineHeight: 20,
        fontWeight: "800",
    },
    card: {
        overflow: "hidden",
        borderRadius: 22,
        padding: spacing.md,
        gap: spacing.md,
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
    },
    cardHeader: {
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: spacing.md,
    },
    cardHeaderCopy: {
        flex: 1,
        gap: spacing.xs,
    },
    cardTitle: {
        color: colors.text,
        fontSize: 19,
        lineHeight: 25,
        fontWeight: "800",
    },
    cardDescription: {
        color: colors.mutedText,
        fontSize: 13,
        lineHeight: 20,
    },
    activeBadge: {
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    activeBadgeText: {
        fontSize: 11,
        lineHeight: 14,
        fontWeight: "800",
        textTransform: "uppercase",
    },
    promoSurface: {
        minHeight: 74,
        borderRadius: 17,
        paddingHorizontal: spacing.md,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: spacing.md,
        backgroundColor: colors.surfaceElevated,
        borderWidth: 1,
        borderColor: colors.border,
    },
    promoCopy: {
        flex: 1,
        gap: 2,
    },
    smallLabel: {
        color: colors.mutedText,
        fontSize: 12,
        lineHeight: 17,
        fontWeight: "600",
    },
    promoCode: {
        color: colors.text,
        fontSize: 22,
        lineHeight: 28,
        fontWeight: "900",
        letterSpacing: 0.7,
    },
    unlinkButton: {
        minHeight: 38,
        borderRadius: 12,
        paddingHorizontal: 12,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: colors.dangerMuted,
    },
    unlinkButtonPressed: {
        opacity: 0.7,
    },
    unlinkButtonText: {
        color: colors.danger,
        fontSize: 13,
        fontWeight: "800",
    },
    promoForm: {
        gap: spacing.sm,
    },
    promoInputRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: spacing.sm,
    },
    promoInput: {
        flex: 1,
        minHeight: 50,
        borderRadius: 15,
        paddingHorizontal: spacing.md,
        color: colors.text,
        fontSize: 15,
        fontWeight: "700",
        backgroundColor: colors.fieldBackground,
        borderWidth: 1,
        borderColor: colors.border,
    },
    primaryButton: {
        minHeight: 50,
        minWidth: 104,
        borderRadius: 15,
        paddingHorizontal: spacing.md,
        alignItems: "center",
        justifyContent: "center",
    },
    primaryButtonDisabled: {
        opacity: 0.45,
    },
    primaryButtonText: {
        fontSize: 14,
        fontWeight: "800",
    },
    suggestionButton: {
        alignSelf: "flex-start",
        minHeight: 38,
        borderRadius: 12,
        paddingHorizontal: 12,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: colors.surfaceElevated,
        borderWidth: 1,
        borderColor: colors.border,
    },
    suggestionButtonPressed: {
        opacity: 0.72,
    },
    suggestionButtonText: {
        color: colors.text,
        fontSize: 13,
        fontWeight: "700",
    },
    progressNumbers: {
        flexDirection: "row",
        alignItems: "flex-end",
        justifyContent: "space-between",
        gap: spacing.md,
    },
    progressValue: {
        color: colors.text,
        fontSize: 28,
        lineHeight: 34,
        fontWeight: "900",
        letterSpacing: -0.7,
    },
    progressTarget: {
        alignItems: "flex-end",
        gap: 2,
    },
    progressTargetValue: {
        color: colors.text,
        fontSize: 16,
        lineHeight: 21,
        fontWeight: "800",
    },
    progressTrack: {
        height: 8,
        overflow: "hidden",
        borderRadius: 999,
        backgroundColor: colors.surfaceMuted,
    },
    progressFill: {
        height: "100%",
        minWidth: 8,
        borderRadius: 999,
    },
    progressHint: {
        color: colors.stateText,
        fontSize: 13,
        lineHeight: 20,
    },
    disclosureButton: {
        minHeight: 48,
        marginHorizontal: -spacing.md,
        marginBottom: -spacing.md,
        paddingHorizontal: spacing.md,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: spacing.md,
        borderTopWidth: 1,
        borderTopColor: colors.divider,
    },
    disclosureButtonPressed: {
        backgroundColor: colors.pressedSurface,
    },
    disclosureText: {
        flex: 1,
        color: colors.text,
        fontSize: 14,
        fontWeight: "700",
    },
    disclosureSymbol: {
        color: colors.mutedText,
        fontSize: 20,
        lineHeight: 24,
        fontWeight: "500",
    },
    ladder: {
        flexDirection: "row",
        flexWrap: "wrap",
        columnGap: spacing.md,
        rowGap: 0,
        paddingTop: spacing.xs,
    },
    ladderItem: {
        flexBasis: "46%",
        flexGrow: 1,
        minHeight: 42,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: spacing.sm,
        borderBottomWidth: 1,
        borderBottomColor: colors.divider,
    },
    ladderAmount: {
        color: colors.mutedText,
        fontSize: 12,
        lineHeight: 17,
        fontWeight: "600",
    },
    ladderPercent: {
        color: colors.text,
        fontSize: 14,
        lineHeight: 19,
        fontWeight: "800",
    },
    ruleList: {
        gap: 0,
    },
    ruleRow: {
        flexDirection: "row",
        gap: 12,
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: colors.divider,
    },
    ruleRowLast: {
        borderBottomWidth: 0,
        paddingBottom: 0,
    },
    ruleDot: {
        width: 8,
        height: 8,
        marginTop: 7,
        borderRadius: 999,
    },
    ruleCopy: {
        flex: 1,
        gap: spacing.xs,
    },
    ruleTitle: {
        color: colors.text,
        fontSize: 15,
        lineHeight: 20,
        fontWeight: "800",
    },
    ruleText: {
        color: colors.mutedText,
        fontSize: 13,
        lineHeight: 20,
    },
    statList: {
        gap: 0,
    },
    statRow: {
        minHeight: 52,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: colors.divider,
    },
    statRowLast: {
        borderBottomWidth: 0,
    },
    statLabel: {
        flex: 1,
        color: colors.mutedText,
        fontSize: 13,
        lineHeight: 19,
    },
    statValue: {
        maxWidth: "52%",
        color: colors.text,
        fontSize: 15,
        lineHeight: 20,
        fontWeight: "800",
        textAlign: "right",
    },
    loading: {
        paddingVertical: spacing.xl,
    },
    promotionStack: {
        gap: spacing.sm,
    },
    promotionRow: {
        minHeight: 72,
        borderRadius: 16,
        padding: spacing.sm,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        backgroundColor: colors.surfaceElevated,
        borderWidth: 1,
        borderColor: colors.border,
    },
    promotionRowPressed: {
        opacity: 0.72,
    },
    promotionImage: {
        width: 54,
        height: 54,
        borderRadius: 12,
        backgroundColor: colors.surfaceMuted,
    },
    promotionCopy: {
        flex: 1,
        gap: 3,
    },
    promotionTitle: {
        color: colors.text,
        fontSize: 14,
        lineHeight: 19,
        fontWeight: "700",
    },
    promotionSubtitle: {
        color: colors.mutedText,
        fontSize: 12,
        lineHeight: 17,
    },
    promotionDiscount: {
        color: colors.discountedPrice,
        fontSize: 15,
        fontWeight: "900",
    },
    promotionArrow: {
        color: colors.mutedText,
        fontSize: 20,
        lineHeight: 24,
    },
})
