import { StyleSheet } from "react-native"

import { colors } from "@/theme/colors"
import { spacing } from "@/theme/spacing"

export const ProfileScreenStyles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: colors.background,
    },
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    content: {
        paddingHorizontal: spacing.md,
        paddingTop: spacing.lg,
        paddingBottom: spacing.xl,
        gap: spacing.lg,
    },
    heroCard: {
        position: "relative",
        overflow: "hidden",
        borderRadius: 28,
        padding: spacing.lg,
        backgroundColor: colors.primary,
        gap: spacing.md,
    },
    heroGlow: {
        position: "absolute",
        width: 220,
        height: 220,
        borderRadius: 999,
        backgroundColor: "rgba(255,255,255,0.10)",
        top: -96,
        right: -72,
    },
    heroTopRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: spacing.md,
    },
    avatarShell: {
        width: 76,
        height: 76,
        borderRadius: 38,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 2,
        borderColor: "rgba(255,255,255,0.35)",
        backgroundColor: "rgba(255,255,255,0.12)",
        padding: 3,
    },
    avatarPressed: {
        opacity: 0.88,
        transform: [{ scale: 0.97 }],
    },
    avatarCrop: {
        width: "100%",
        height: "100%",
        borderRadius: 999,
        overflow: "hidden",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#eef7ff",
    },
    avatarImage: {
        width: "100%",
        height: "100%",
        borderRadius: 999,
    },
    avatarText: {
        color: colors.primary,
        fontSize: 28,
        fontWeight: "800",
    },
    heroCopy: {
        flex: 1,
        gap: spacing.xs,
    },
    heroInfoButton: {
        alignSelf: "flex-start",
        borderRadius: 12,
        marginHorizontal: -spacing.xs,
        paddingHorizontal: spacing.xs,
        paddingVertical: 2,
    },
    heroInfoButtonPressed: {
        backgroundColor: "rgba(255,255,255,0.12)",
    },
    eyebrow: {
        color: "rgba(255,255,255,0.76)",
        fontSize: 12,
        fontWeight: "700",
        letterSpacing: 1.1,
        textTransform: "uppercase",
    },
    name: {
        color: "#ffffff",
        fontSize: 28,
        fontWeight: "800",
    },
    handle: {
        color: "rgba(255,255,255,0.82)",
        fontSize: 15,
        fontWeight: "500",
    },
    subtitle: {
        color: "rgba(255,255,255,0.9)",
        fontSize: 15,
        lineHeight: 24,
        maxWidth: 280,
    },
    badgeRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: spacing.sm,
    },
    badge: {
        borderRadius: 999,
        backgroundColor: "#d7f7e3",
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
    },
    badgeText: {
        color: "#0f6a37",
        fontSize: 13,
        fontWeight: "700",
    },
    badgeSecondary: {
        borderRadius: 999,
        backgroundColor: "rgba(255,255,255,0.14)",
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.18)",
    },
    badgeSecondaryText: {
        color: "#ffffff",
        fontSize: 13,
        fontWeight: "700",
    },
    metricsGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: spacing.md,
    },
    metricCard: {
        minHeight: 136,
        borderRadius: 20,
        padding: spacing.md,
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        justifyContent: "space-between",
        boxShadow: "0px 6px 12px rgba(11, 31, 51, 0.04)",
        elevation: 1,
    },
    metricLabel: {
        color: colors.mutedText,
        fontSize: 13,
        fontWeight: "600",
    },
    metricValue: {
        color: colors.text,
        fontSize: 22,
        lineHeight: 30,
        fontWeight: "800",
    },
    metricValueCompact: {
        fontSize: 18,
        lineHeight: 24,
    },
    sectionCard: {
        borderRadius: 24,
        padding: spacing.lg,
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        gap: spacing.md,
        boxShadow: "0px 6px 12px rgba(11, 31, 51, 0.03)",
        elevation: 1,
    },
    sectionTitle: {
        color: colors.text,
        fontSize: 20,
        fontWeight: "800",
    },
    sectionHeader: {
        alignItems: "flex-start",
        flexDirection: "row",
        gap: spacing.md,
        justifyContent: "space-between",
    },
    sectionHeaderCopy: {
        flex: 1,
        gap: spacing.xs,
    },
    sectionDescription: {
        color: colors.mutedText,
        fontSize: 14,
        lineHeight: 24,
    },
    statusBadge: {
        borderRadius: 999,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
    },
    statusBadgeSuccess: {
        backgroundColor: "#dff7e8",
    },
    statusBadgeMuted: {
        backgroundColor: "#eef2f7",
    },
    statusBadgeText: {
        fontSize: 12,
        fontWeight: "800",
        textTransform: "uppercase",
        letterSpacing: 0.6,
    },
    statusBadgeTextSuccess: {
        color: "#0f6a37",
    },
    statusBadgeTextMuted: {
        color: colors.mutedText,
    },
    detailRow: {
        gap: spacing.xs,
    },
    detailStack: {
        gap: spacing.md,
    },
    detailRowButton: {
        borderRadius: 16,
        marginHorizontal: -spacing.sm,
        paddingHorizontal: spacing.sm,
        paddingVertical: spacing.sm,
    },
    detailRowButtonPressed: {
        backgroundColor: "#edf4fb",
    },
    detailLabel: {
        color: colors.mutedText,
        fontSize: 13,
        fontWeight: "700",
        textTransform: "uppercase",
        letterSpacing: 0.6,
    },
    detailValue: {
        color: colors.text,
        fontSize: 17,
        fontWeight: "600",
    },
    detailDivider: {
        height: 1,
        backgroundColor: colors.border,
    },
    loadingBox: {
        alignItems: "center",
        justifyContent: "center",
        minHeight: 72,
    },
    subsection: {
        gap: spacing.sm,
    },
    subsectionTitle: {
        color: colors.text,
        fontSize: 16,
        fontWeight: "800",
    },
    emptyHint: {
        color: colors.mutedText,
        fontSize: 14,
        lineHeight: 22,
    },
    websiteChipRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: spacing.sm,
    },
    websiteChip: {
        borderRadius: 18,
        backgroundColor: "#f3f7fc",
        borderWidth: 1,
        borderColor: "#d7e2f0",
        minWidth: 96,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
        gap: 2,
    },
    websiteChipValue: {
        color: colors.text,
        fontSize: 18,
        fontWeight: "800",
    },
    websiteChipLabel: {
        color: colors.mutedText,
        fontSize: 12,
        fontWeight: "700",
    },
    tagList: {
        gap: spacing.sm,
    },
    tag: {
        borderRadius: 18,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: "#fbfcfe",
        gap: 4,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
    },
    tagTitle: {
        color: colors.text,
        fontSize: 15,
        fontWeight: "700",
    },
    tagSubtitle: {
        color: colors.mutedText,
        fontSize: 13,
        lineHeight: 18,
    },
    formGroup: {
        gap: spacing.sm,
    },
    formLabel: {
        color: colors.text,
        fontSize: 14,
        fontWeight: "700",
    },
    formInput: {
        backgroundColor: colors.surface,
        borderColor: colors.border,
        borderRadius: 14,
        borderWidth: 1,
        color: colors.text,
        fontSize: 16,
        minHeight: 50,
        paddingHorizontal: spacing.md,
    },
    formHint: {
        color: colors.mutedText,
        fontSize: 13,
        lineHeight: 21,
    },
    errorBox: {
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#fecdd3",
        backgroundColor: "#fff4f6",
        gap: spacing.sm,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
    },
    errorText: {
        color: "#be123c",
        fontSize: 14,
        lineHeight: 20,
    },
    primaryActionButton: {
        minHeight: 50,
        borderRadius: 16,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: colors.primary,
        paddingHorizontal: spacing.md,
    },
    primaryActionButtonPressed: {
        opacity: 0.84,
    },
    primaryActionButtonText: {
        color: "#ffffff",
        fontSize: 16,
        fontWeight: "800",
    },
    secondaryInlineButton: {
        alignSelf: "flex-start",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#f0a3b1",
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
    },
    secondaryInlineButtonPressed: {
        opacity: 0.8,
    },
    secondaryInlineButtonText: {
        color: "#be123c",
        fontSize: 14,
        fontWeight: "700",
    },
    signOutButton: {
        minHeight: 50,
        borderRadius: 16,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: colors.primary,
        paddingHorizontal: spacing.md,
    },
    signOutButtonPressed: {
        opacity: 0.84,
    },
    signOutButtonText: {
        color: "#ffffff",
        fontSize: 16,
        fontWeight: "800",
    },
    avatarViewerBackdrop: {
        flex: 1,
        backgroundColor: "rgba(4, 10, 18, 0.92)",
        alignItems: "center",
        justifyContent: "center",
        padding: spacing.lg,
    },
    avatarViewerDismissArea: {
        ...StyleSheet.absoluteFillObject,
    },
    avatarViewerContent: {
        width: "100%",
        alignItems: "center",
        gap: spacing.lg,
        zIndex: 1,
    },
    avatarViewerFrame: {
        width: 280,
        height: 280,
        borderRadius: 999,
        overflow: "hidden",
        borderWidth: 3,
        borderColor: "rgba(255,255,255,0.16)",
        backgroundColor: "#d9ecfb",
        alignItems: "center",
        justifyContent: "center",
    },
    avatarViewerImage: {
        width: "100%",
        height: "100%",
        borderRadius: 999,
    },
    avatarViewerPlaceholder: {
        width: "100%",
        height: "100%",
        borderRadius: 999,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#d9ecfb",
    },
    avatarViewerPlaceholderText: {
        color: colors.primary,
        fontSize: 88,
        fontWeight: "800",
    },
    avatarViewerName: {
        color: "#ffffff",
        fontSize: 24,
        fontWeight: "800",
        textAlign: "center",
    },
    avatarViewerActions: {
        width: "100%",
        maxWidth: 320,
        gap: spacing.sm,
    },
    avatarViewerPrimaryAction: {
        minHeight: 50,
        borderRadius: 16,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#ffffff",
        paddingHorizontal: spacing.md,
    },
    avatarViewerPrimaryActionText: {
        color: colors.primary,
        fontSize: 16,
        fontWeight: "800",
    },
    avatarViewerDestructiveAction: {
        minHeight: 50,
        borderRadius: 16,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#d74b5c",
        paddingHorizontal: spacing.md,
    },
    avatarViewerDestructiveActionText: {
        color: "#ffffff",
        fontSize: 16,
        fontWeight: "800",
    },
    avatarViewerActionPressed: {
        opacity: 0.82,
    },
    avatarViewerActionDisabled: {
        opacity: 0.42,
    },
})
