from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class SystemRole:
    code: str
    name_ru: str
    name_en: str
    description_ru: str
    description_en: str
    permissions: tuple[str, ...]


SYSTEM_ROLES: tuple[SystemRole, ...] = (
    SystemRole(
        code="superadmin",
        name_ru="Суперадминистратор",
        name_en="Super administrator",
        description_ru="Полный доступ, управление сотрудниками, безопасностью и аудитом.",
        description_en="Full access, including staff, security, and audit management.",
        permissions=("*",),
    ),
    SystemRole(
        code="sales",
        name_ru="Продажи и CRM",
        name_en="Sales and CRM",
        description_ru="Заказы, клиенты, лиды, задачи и коммуникации с покупателями.",
        description_en="Orders, customers, leads, tasks, and customer communications.",
        permissions=(
            "dashboard.read",
            "orders.read",
            "orders.transition",
            "orders.recover",
            "customers.read",
            "customers.manage",
            "customers.notes",
            "tasks.read",
            "tasks.manage",
            "segments.read",
            "automation.read",
            "sla.read",
            "alerts.read",
            "ai_chats.read",
            "support.read",
            "support.reply",
            "support.assign",
            "leads.read",
            "leads.manage",
            "analytics.read",
            "exports.read",
        ),
    ),
    SystemRole(
        code="support",
        name_ru="Поддержка",
        name_en="Support",
        description_ru="Диалоги поддержки, контекст клиента, задачи, лиды и контроль SLA.",
        description_en="Support conversations, customer context, tasks, leads, and SLA monitoring.",
        permissions=(
            "dashboard.read",
            "orders.read",
            "customers.read",
            "customers.notes",
            "tasks.read",
            "tasks.manage",
            "reviews.read",
            "community.read",
            "ai_chats.read",
            "support.read",
            "support.reply",
            "support.assign",
            "leads.read",
            "leads.manage",
            "sla.read",
            "alerts.read",
        ),
    ),
    SystemRole(
        code="content",
        name_ru="Контент и витрина",
        name_en="Content and storefront",
        description_ru="Каталог, категории, баннеры, бизнес-контент и модерация отзывов.",
        description_en="Catalog, categories, banners, business content, and review moderation.",
        permissions=(
            "dashboard.read",
            "catalog.read",
            "catalog.merchandise",
            "categories.manage",
            "reviews.read",
            "reviews.moderate",
            "banners.manage",
            "alerts.read",
            "exports.read",
        ),
    ),
    SystemRole(
        code="marketing",
        name_ru="Маркетинг",
        name_en="Marketing",
        description_ru="Сегменты, кампании, триггерные коммуникации, рефералы и аналитика.",
        description_en="Segments, campaigns, triggered communications, referrals, and analytics.",
        permissions=(
            "dashboard.read",
            "customers.read",
            "catalog.read",
            "reviews.read",
            "referrals.read",
            "notifications.manage",
            "segments.read",
            "segments.manage",
            "campaigns.read",
            "campaigns.manage",
            "campaigns.send",
            "leads.read",
            "ai_chats.read",
            "analytics.read",
            "alerts.read",
            "exports.read",
        ),
    ),
    SystemRole(
        code="logistics",
        name_ru="Логистика и операции",
        name_en="Logistics and operations",
        description_ru="Исполнение заказов, интеграции, операционные задачи и автоматизация.",
        description_en="Order fulfillment, integrations, operational tasks, and automation.",
        permissions=(
            "dashboard.read",
            "orders.read",
            "orders.transition",
            "orders.recover",
            "customers.read",
            "tasks.read",
            "tasks.manage",
            "catalog.read",
            "automation.read",
            "automation.manage",
            "sla.read",
            "alerts.read",
            "alerts.manage",
            "integrations.read",
            "integrations.retry",
            "exports.read",
        ),
    ),
    SystemRole(
        code="analyst",
        name_ru="Аналитик / аудитор",
        name_en="Analyst / auditor",
        description_ru="Сквозной доступ только на чтение, аналитика, экспорт и журнал аудита.",
        description_en="Cross-functional read-only access, analytics, exports, and audit log.",
        permissions=(
            "dashboard.read",
            "orders.read",
            "customers.read",
            "tasks.read",
            "segments.read",
            "campaigns.read",
            "automation.read",
            "sla.read",
            "alerts.read",
            "catalog.read",
            "reviews.read",
            "referrals.read",
            "community.read",
            "ai_chats.read",
            "support.read",
            "leads.read",
            "analytics.read",
            "integrations.read",
            "audit.read",
            "exports.read",
        ),
    ),
)

SYSTEM_ROLE_BY_CODE = {role.code: role for role in SYSTEM_ROLES}
ASSIGNABLE_ROLE_CODES = frozenset(SYSTEM_ROLE_BY_CODE)

