import { StyleSheet } from "react-native"

import type { ThemePalette } from "@/theme/colors"
import { spacing } from "@/theme/spacing"

const glassShadow = {
    shadowColor: "#0C2A3A",
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { height: 8, width: 0 },
    elevation: 10,
} as const

const liquidGlassBlue = {
    backgroundColor: "rgba(255,255,255,0.95)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.78)",
} as const

const liquidGlassNeutral = {
    backgroundColor: "rgba(255,255,255,0.95)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.74)",
} as const

export const createChatScreenStyles = (colors: ThemePalette) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.surface,
    },
    keyboardContent: {
        flex: 1,
    },
    keyboardLayer: {
        flex: 1,
    },
    content: {
        flex: 1,
        position: "relative",
        backgroundColor: colors.surfaceSoft,
    },
    backgroundImage: {
        ...StyleSheet.absoluteFillObject,
    },
    backgroundImageHidden: {
        opacity: 0,
    },
    backgroundImageAsset: {
        opacity: 1,
    },
    backgroundScrim: {
        ...StyleSheet.absoluteFillObject,
    },
    backgroundScrimLight: {
        backgroundColor: "rgba(226,251,226,0.52)",
    },
    backgroundScrimDark: {
        backgroundColor: "rgba(15,21,29,0.42)",
    },
    dialogTopBlur: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        zIndex: 6,
    },
    dialogBottomBlur: {
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 6,
    },
    edgeTintTop: {
        position: "absolute",
        left: 0,
        right: 0,
        top: 0,
        zIndex: 7,
    },
    edgeTintBottom: {
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 7,
    },
    edgeTintTopLight: {
        backgroundColor: "rgba(245,255,248,0.26)",
    },
    edgeTintTopDark: {
        backgroundColor: "rgba(9,16,24,0.44)",
    },
    edgeTintBottomLight: {
        backgroundColor: "rgba(246,255,250,0.3)",
    },
    edgeTintBottomDark: {
        backgroundColor: "rgba(9,16,24,0.5)",
    },
    topBarRow: {
        position: "absolute",
        left: spacing.md,
        right: spacing.md,
        zIndex: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-start",
        gap: spacing.sm,
    },
    topBackButton: {
        width: 48,
        height: 48,
        borderRadius: 24,
        ...liquidGlassBlue,
        alignItems: "center",
        justifyContent: "center",
        ...glassShadow,
    },
    loadingWrap: {
        flex: 1,
        backgroundColor: colors.surface,
        alignItems: "center",
        justifyContent: "center",
    },
    stateWrap: {
        flex: 1,
        backgroundColor: colors.surface,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: spacing.md,
    },
    initialStateOverlay: {
        ...StyleSheet.absoluteFillObject,
        zIndex: 9,
        backgroundColor: colors.surface,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: spacing.md,
    },
    messagesScroll: {
        flex: 1,
        backgroundColor: "transparent",
    },
    messagesContent: {
        flexGrow: 1,
        paddingHorizontal: spacing.sm,
        justifyContent: "flex-end",
    },
    messageList: {
        gap: spacing.sm,
    },
    messageBlock: {
        gap: spacing.xs,
    },
    dayChip: {
        alignSelf: "center",
        borderRadius: 13,
        backgroundColor: "rgba(100,129,113,0.5)",
        paddingHorizontal: spacing.sm,
        paddingVertical: 4,
        marginBottom: spacing.xs,
    },
    dayChipText: {
        color: "#F5FFFA",
        fontSize: 12,
        lineHeight: 14,
        fontWeight: "600",
    },
    emptyCenterOverlay: {
        ...StyleSheet.absoluteFillObject,
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1,
        paddingHorizontal: spacing.md,
    },
    emptyBubble: {
        maxWidth: "88%",
        borderRadius: 18,
        backgroundColor: "rgba(255,255,255,0.9)",
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
    },
    emptyText: {
        color: "#1E2328",
        fontSize: 15,
        lineHeight: 20,
        textAlign: "center",
    },
    messageBubble: {
        maxWidth: "83%",
        borderRadius: 18,
        paddingHorizontal: 12,
        paddingTop: 8,
        paddingBottom: 7,
    },
    messageBubbleWithMedia: {
        paddingHorizontal: 4,
        paddingTop: 4,
    },
    userMessageBubble: {
        alignSelf: "flex-end",
        backgroundColor: "rgba(228,255,203,0.92)",
        borderBottomRightRadius: 8,
    },
    aiMessageBubble: {
        alignSelf: "flex-start",
        backgroundColor: "rgba(255,255,255,0.96)",
        borderBottomLeftRadius: 8,
    },
    failedMessageBubble: {
        backgroundColor: "rgba(255,244,246,0.96)",
    },
    messageText: {
        color: "#15191E",
        fontSize: 16,
        lineHeight: 22,
    },
    messageMarkdownBaseText: {
        fontSize: 16,
        lineHeight: 22,
    },
    messageMarkdownWithMedia: {
        marginTop: 7,
        marginHorizontal: 8,
    },
    messageCaptionText: {
        marginTop: 7,
        marginHorizontal: 8,
    },
    messageBubblePressed: {
        opacity: 0.88,
    },
    userMessageText: {
        color: "#17311C",
    },
    messageAttachmentStack: {
        gap: 6,
    },
    messageImageStack: {
        gap: 4,
    },
    messageImageAttachment: {
        overflow: "hidden",
        borderRadius: 15,
        backgroundColor: "rgba(0,0,0,0.08)",
    },
    messageDocumentStack: {
        gap: 5,
    },
    messageDocumentAttachment: {
        minWidth: 188,
        maxWidth: 260,
        minHeight: 52,
        borderRadius: 14,
        backgroundColor: "rgba(21,151,223,0.09)",
        flexDirection: "row",
        alignItems: "center",
        gap: 9,
        paddingHorizontal: 9,
        paddingVertical: 8,
    },
    userMessageDocumentAttachment: {
        backgroundColor: "rgba(47,111,54,0.1)",
    },
    messageDocumentIcon: {
        width: 32,
        height: 32,
        borderRadius: 10,
        backgroundColor: "rgba(255,255,255,0.74)",
        alignItems: "center",
        justifyContent: "center",
    },
    messageDocumentName: {
        flex: 1,
        color: "#2B658F",
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "700",
    },
    userMessageDocumentName: {
        color: "#2F6F36",
    },
    attachmentList: {
        gap: 5,
        marginTop: spacing.xs,
    },
    attachmentName: {
        color: "#2B658F",
        fontSize: 14,
        lineHeight: 18,
    },
    userAttachmentName: {
        color: "#2F6F36",
    },
    messageMeta: {
        alignSelf: "flex-end",
        marginTop: spacing.xs,
        color: "rgba(36,43,47,0.58)",
        fontSize: 11,
        lineHeight: 13,
    },
    userMessageMeta: {
        color: "rgba(23,49,28,0.58)",
    },
    pendingMessageMeta: {
        color: "rgba(23,49,28,0.42)",
    },
    failedMessageMeta: {
        color: colors.danger,
    },
    typingBubble: {
        minWidth: 58,
        paddingHorizontal: 14,
        paddingVertical: 11,
    },
    typingDotsRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
    },
    typingDot: {
        width: 7,
        height: 7,
        borderRadius: 4,
        backgroundColor: "rgba(36,43,47,0.58)",
    },
    aiInteractiveWrap: {
        alignSelf: "flex-start",
        width: "86%",
        maxWidth: 360,
        gap: spacing.xs,
    },
    aiProductCard: {
        overflow: "hidden",
        borderRadius: 8,
        backgroundColor: "rgba(255,255,255,0.94)",
        borderWidth: 1,
        borderColor: "rgba(217,227,235,0.86)",
        padding: 10,
        gap: 8,
    },
    aiProductCardPressed: {
        opacity: 0.9,
    },
    aiProductHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 0,
    },
    aiProductImage: {
        width: 54,
        height: 54,
        borderRadius: 7,
        backgroundColor: "rgba(0,0,0,0.06)",
    },
    aiProductTextWrap: {
        flex: 1,
        gap: 0,
    },
    aiProductTitle: {
        color: "#15191E",
        fontSize: 16,
        lineHeight: 20,
        fontWeight: "800",
    },
    aiProductReason: {
        color: "rgba(36,43,47,0.68)",
        fontSize: 12,
        lineHeight: 16,
    },
    aiVariantSelectorCard: {
        borderRadius: 7,
        backgroundColor: "transparent",
        gap: 7,
        padding: 0,
    },
    aiVariantSelectorRow: {
        gap: 7,
    },
    aiVariantSelectorOption: {
        alignItems: "center",
        width: 52,
    },
    aiVariantSelectorOptionSelected: {
        opacity: 1,
    },
    aiVariantSelectorOptionDisabled: {
        opacity: 0.42,
    },
    aiVariantSelectorOptionPressed: {
        opacity: 0.8,
    },
    aiVariantSelectorImage: {
        width: 52,
        height: 52,
        borderRadius: 10,
        backgroundColor: "rgba(245,247,249,0.92)",
    },
    aiVariantSelectorImageSelected: {
        borderWidth: 1.5,
        borderColor: colors.primary,
    },
    aiSelectedVariantMetaRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 8,
    },
    aiSelectedVariantMetaCopy: {
        flex: 1,
        minWidth: 0,
        gap: 1,
    },
    aiSelectedVariantName: {
        color: "#15191E",
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "800",
    },
    aiSelectedVariantStock: {
        color: "rgba(36,43,47,0.58)",
        fontSize: 11,
        lineHeight: 14,
        fontWeight: "700",
    },
    aiSelectedVariantPrice: {
        color: "#15191E",
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "900",
    },
    aiSelectedVariantBasketButton: {
        width: "100%",
        minHeight: 34,
        borderRadius: 8,
        backgroundColor: colors.primary,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 10,
    },
    aiSelectedVariantBasketButtonPressed: {
        opacity: 0.84,
    },
    aiSelectedVariantBasketButtonText: {
        color: colors.onPrimary,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "900",
        textAlign: "center",
    },
    aiSelectedVariantBasketButtonTextDisabled: {
        color: "rgba(255,255,255,0.86)",
    },
    aiSelectedVariantQuantityControl: {
        width: "100%",
        minHeight: 34,
        borderRadius: 8,
        backgroundColor: colors.primary,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        overflow: "hidden",
    },
    aiSelectedVariantQuantityButton: {
        width: 44,
        minHeight: 34,
        alignItems: "center",
        justifyContent: "center",
    },
    aiSelectedVariantQuantityButtonPressed: {
        backgroundColor: "rgba(255,255,255,0.14)",
    },
    aiSelectedVariantQuantityButtonDisabled: {
        opacity: 0.38,
    },
    aiSelectedVariantQuantityButtonText: {
        color: colors.onPrimary,
        fontSize: 22,
        lineHeight: 24,
        fontWeight: "900",
    },
    aiSelectedVariantQuantityValueWrap: {
        flex: 1,
        minHeight: 34,
        alignItems: "center",
        justifyContent: "center",
    },
    aiSelectedVariantQuantityValue: {
        color: colors.onPrimary,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "900",
        textAlign: "center",
    },
    aiVariantControlDisabled: {
        opacity: 0.62,
    },
    aiActionRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 6,
        width: "100%",
        alignItems: "stretch",
    },
    aiActionKeyboard: {
        gap: 6,
        width: "100%",
    },
    aiActionKeyboardRow: {
        flexDirection: "row",
        gap: 6,
        width: "100%",
        alignItems: "stretch",
    },
    aiActionKeyboardCell: {
        flex: 1,
        minWidth: 0,
        gap: 4,
        alignItems: "stretch",
    },
    aiVariantActionRow: {
        flexBasis: "48%",
        flexGrow: 1,
        minWidth: 0,
        flexDirection: "column",
        gap: 4,
        alignItems: "stretch",
    },
    aiQuantityStepper: {
        width: "100%",
        minHeight: 30,
        borderRadius: 8,
        backgroundColor: "rgba(21,151,223,0.08)",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        overflow: "hidden",
    },
    aiQuantityButton: {
        width: 30,
        height: "100%",
        minHeight: 30,
        alignItems: "center",
        justifyContent: "center",
    },
    aiQuantityButtonDisabled: {
        opacity: 0.4,
    },
    aiQuantityButtonText: {
        color: colors.primary,
        fontSize: 16,
        lineHeight: 18,
        fontWeight: "900",
    },
    aiQuantityValue: {
        flex: 1,
        color: "#15191E",
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "800",
        textAlign: "center",
    },
    aiVariantActionButton: {
        width: "100%",
    },
    aiKeyboardActionButton: {
        width: "100%",
    },
    aiFullWidthActionButton: {
        flexBasis: "48%",
        flexGrow: 1,
        minWidth: 0,
    },
    aiActionButton: {
        minHeight: 32,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    aiActionButtonSecondary: {
        backgroundColor: colors.primary,
    },
    aiActionButtonPrimary: {
        backgroundColor: colors.primary,
    },
    aiActionButtonPressed: {
        opacity: 0.82,
    },
    aiActionButtonDisabled: {
        opacity: 0.62,
    },
    aiActionButtonText: {
        color: colors.onPrimary,
        fontSize: 12,
        lineHeight: 15,
        fontWeight: "800",
        textAlign: "center",
    },
    aiActionButtonPrimaryText: {
        color: colors.onPrimary,
    },
    aiDraftCard: {
        overflow: "hidden",
        borderRadius: 8,
        backgroundColor: "rgba(255,255,255,0.96)",
        borderWidth: 1,
        borderColor: "rgba(194,213,200,0.92)",
        padding: 10,
        gap: 8,
    },
    aiDraftTitle: {
        color: "#15191E",
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "900",
    },
    aiDraftNote: {
        color: "rgba(36,43,47,0.68)",
        fontSize: 12,
        lineHeight: 16,
    },
    aiDraftItems: {
        gap: 6,
    },
    aiDraftItemRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    aiDraftItemImage: {
        width: 38,
        height: 38,
        borderRadius: 7,
        backgroundColor: "rgba(0,0,0,0.06)",
    },
    aiDraftItemText: {
        flex: 1,
    },
    aiDraftItemName: {
        color: "#15191E",
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "800",
    },
    aiDraftItemMeta: {
        color: "rgba(36,43,47,0.62)",
        fontSize: 12,
        lineHeight: 15,
    },
    aiDraftItemPrice: {
        color: "#15191E",
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "900",
    },
    aiDraftTotalRow: {
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: "rgba(60,60,67,0.16)",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingTop: 7,
    },
    aiDraftTotalLabel: {
        color: "rgba(36,43,47,0.7)",
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "700",
    },
    aiDraftTotalValue: {
        color: "#15191E",
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "900",
    },
    aiFollowUpText: {
        color: "#15191E",
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "700",
        borderRadius: 8,
        backgroundColor: "rgba(255,255,255,0.9)",
        paddingHorizontal: 10,
        paddingVertical: 8,
    },
    inlineErrorWrap: {
        position: "absolute",
        left: spacing.md,
        right: spacing.md,
        zIndex: 13,
    },
    inlineError: {
        alignSelf: "center",
        borderRadius: 12,
        paddingHorizontal: spacing.sm,
        paddingVertical: spacing.xs,
        backgroundColor: "rgba(185,28,28,0.94)",
        color: "#FFF9F9",
        fontSize: 12,
        lineHeight: 16,
    },
    composerDock: {
        position: "absolute",
        left: spacing.sm,
        right: spacing.sm,
        bottom: 0,
        zIndex: 14,
        paddingTop: spacing.xs,
    },
    composerRow: {
        flexDirection: "row",
        alignItems: "flex-end",
        gap: spacing.sm,
    },
    voiceStatusPill: {
        alignSelf: "center",
        minHeight: 34,
        borderRadius: 17,
        ...liquidGlassNeutral,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        paddingHorizontal: spacing.sm,
        marginBottom: spacing.xs,
        ...glassShadow,
    },
    voiceStatusDot: {
        width: 9,
        height: 9,
        borderRadius: 5,
        backgroundColor: "#FF3B30",
    },
    voiceStatusText: {
        color: "#111417",
        fontSize: 13,
        lineHeight: 16,
        fontWeight: "700",
    },
    circleButton: {
        width: 46,
        height: 46,
        borderRadius: 23,
        ...liquidGlassBlue,
        alignItems: "center",
        justifyContent: "center",
        overflow: "visible",
        ...glassShadow,
    },
    circleButtonPressable: {
        width: 46,
        height: 46,
        borderRadius: 23,
        overflow: "visible",
    },
    circleButtonPressed: {
        opacity: 0.86,
    },
    composerInputWrap: {
        flex: 1,
        minHeight: 46,
        maxHeight: 118,
        borderRadius: 23,
        ...liquidGlassNeutral,
        flexDirection: "row",
        alignItems: "flex-end",
        paddingLeft: spacing.md,
        paddingRight: spacing.sm,
        paddingVertical: 3,
        ...glassShadow,
    },
    composerInput: {
        flex: 1,
        minHeight: 38,
        maxHeight: 96,
        color: "#111417",
        fontSize: 17,
        lineHeight: 21,
        paddingVertical: spacing.sm,
        paddingRight: spacing.xs,
    },
    stickerButton: {
        width: 30,
        height: 38,
        alignItems: "center",
        justifyContent: "center",
    },
    emojiPicker: {
        borderRadius: 20,
        ...liquidGlassNeutral,
        paddingHorizontal: spacing.sm,
        paddingTop: spacing.sm,
        paddingBottom: 6,
        marginBottom: spacing.xs,
        ...glassShadow,
    },
    emojiPickerTitle: {
        color: "rgba(36,43,47,0.66)",
        fontSize: 11,
        lineHeight: 14,
        fontWeight: "800",
        marginBottom: 4,
        marginLeft: 5,
    },
    emojiPickerGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
    },
    emojiPickerButton: {
        width: "12.5%",
        minHeight: 34,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 10,
    },
    emojiPickerButtonPressed: {
        backgroundColor: "rgba(21,151,223,0.12)",
    },
    emojiPickerEmoji: {
        fontSize: 23,
        lineHeight: 29,
    },
    sendButtonDisabled: {
        opacity: 0.6,
    },
    sendButtonIconLayer: {
        alignItems: "center",
        justifyContent: "center",
    },
    sendButtonMicIconWrap: {
        alignItems: "center",
        justifyContent: "center",
        transform: [{ translateY: 0.5 }],
    },
    sendButtonRecordingLayer: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: 23,
        backgroundColor: "#FF3B30",
    },
    sendButtonSpinnerLayer: {
        ...StyleSheet.absoluteFillObject,
        alignItems: "center",
        justifyContent: "center",
    },
    queuedAttachmentScroll: {
        marginBottom: spacing.xs,
    },
    queuedAttachmentContent: {
        gap: spacing.xs,
        paddingHorizontal: 2,
    },
    queuedAttachmentChip: {
        maxWidth: 196,
        minHeight: 38,
        borderRadius: 19,
        ...liquidGlassNeutral,
        flexDirection: "row",
        alignItems: "center",
        gap: 7,
        paddingLeft: 8,
        paddingRight: 5,
        ...glassShadow,
    },
    queuedAttachmentIcon: {
        width: 24,
        height: 24,
        alignItems: "center",
        justifyContent: "center",
    },
    queuedAttachmentThumbnail: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: "rgba(0,0,0,0.08)",
    },
    queuedAttachmentName: {
        maxWidth: 116,
        color: "#111417",
        fontSize: 13,
        lineHeight: 16,
        fontWeight: "600",
    },
    queuedAttachmentRemove: {
        width: 27,
        height: 27,
        borderRadius: 14,
        ...liquidGlassBlue,
        alignItems: "center",
        justifyContent: "center",
    },
    attachmentModalRoot: {
        flex: 1,
        justifyContent: "flex-end",
    },
    attachmentBackdrop: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(0,0,0,0.18)",
    },
    attachmentSheet: {
        overflow: "hidden",
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        backgroundColor: "rgba(230,241,250,0.72)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.54)",
        shadowColor: "#0C2A3A",
        shadowOpacity: 0.22,
        shadowRadius: 18,
        shadowOffset: { height: -6, width: 0 },
        elevation: 12,
    },
    attachmentHandle: {
        position: "absolute",
        top: 10,
        zIndex: 8,
        alignSelf: "center",
        width: 44,
        height: 5,
        borderRadius: 3,
        backgroundColor: "rgba(0,0,0,0.1)",
    },
    attachmentSheetHeader: {
        position: "absolute",
        top: 24,
        left: spacing.md,
        right: spacing.md,
        zIndex: 7,
        minHeight: 58,
        borderRadius: 29,
        ...liquidGlassNeutral,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 4,
        padding: 4,
        ...glassShadow,
    },
    attachmentHeaderButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: "transparent",
        alignItems: "center",
        justifyContent: "center",
    },
    attachmentHeaderSpacer: {
        width: 50,
        height: 50,
    },
    attachmentTitleButton: {
        flex: 1,
        minHeight: 50,
        borderRadius: 25,
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: 4,
        paddingHorizontal: spacing.sm,
    },
    attachmentSheetTitle: {
        maxWidth: 210,
        color: "#050506",
        fontSize: 20,
        lineHeight: 24,
        fontWeight: "800",
        textAlign: "center",
    },
    attachmentAddButton: {
        minWidth: 54,
        height: 42,
        borderRadius: 21,
        backgroundColor: "rgba(32,153,220,0.58)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.66)",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: spacing.sm,
        ...glassShadow,
    },
    attachmentAddButtonText: {
        color: colors.onPrimary,
        fontSize: 14,
        lineHeight: 17,
        fontWeight: "800",
    },
    attachmentSheetBody: {
        ...StyleSheet.absoluteFillObject,
        zIndex: 1,
    },
    photoSheetBody: {
        flex: 1,
    },
    photoGrid: {
        flex: 1,
    },
    photoGridContent: {
        alignItems: "flex-start",
        width: "100%",
    },
    photoGridHeroRow: {
        flexDirection: "row",
        alignItems: "flex-start",
        width: "100%",
    },
    photoGridHeroPhotos: {
        flexDirection: "row",
        flexWrap: "wrap",
    },
    photoGridWrap: {
        flexDirection: "row",
        flexWrap: "wrap",
        width: "100%",
    },
    cameraTile: {
        overflow: "hidden",
        backgroundColor: "#111820",
        alignItems: "center",
        justifyContent: "center",
    },
    cameraTilePreview: {
        ...StyleSheet.absoluteFillObject,
    },
    cameraTileScrim: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(0,0,0,0.08)",
    },
    cameraTileIcon: {
        width: 70,
        height: 70,
        borderRadius: 35,
        backgroundColor: "rgba(255,255,255,0.16)",
        alignItems: "center",
        justifyContent: "center",
    },
    attachmentLoadingWrap: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
    },
    attachmentPermissionWrap: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: spacing.lg,
        gap: spacing.sm,
    },
    attachmentPermissionTitle: {
        color: "#101214",
        fontSize: 18,
        lineHeight: 22,
        fontWeight: "800",
        textAlign: "center",
    },
    attachmentPermissionText: {
        color: "#697177",
        fontSize: 14,
        lineHeight: 20,
        textAlign: "center",
    },
    attachmentPermissionButton: {
        minHeight: 44,
        borderRadius: 22,
        backgroundColor: "rgba(32,153,220,0.54)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.64)",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: spacing.md,
        ...glassShadow,
    },
    attachmentPermissionButtonText: {
        color: colors.onPrimary,
        fontSize: 15,
        lineHeight: 18,
        fontWeight: "800",
    },
    photoTile: {
        overflow: "hidden",
        backgroundColor: "rgba(0,0,0,0.06)",
    },
    photoTileImage: {
        width: "100%",
        height: "100%",
    },
    photoSelectionCircle: {
        position: "absolute",
        top: 9,
        right: 9,
        width: 28,
        height: 28,
        borderRadius: 14,
        borderWidth: 2,
        borderColor: "rgba(255,255,255,0.92)",
        backgroundColor: "rgba(0,0,0,0.12)",
        alignItems: "center",
        justifyContent: "center",
    },
    photoSelectionCircleActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primary,
    },
    photoSelectionText: {
        color: colors.onPrimary,
        fontSize: 13,
        lineHeight: 16,
        fontWeight: "900",
    },
    fileSheetBody: {
        flex: 1,
        paddingHorizontal: spacing.md,
        paddingTop: 104,
    },
    attachmentActionCard: {
        overflow: "hidden",
        borderRadius: 24,
        ...liquidGlassNeutral,
        ...glassShadow,
    },
    attachmentActionRow: {
        minHeight: 72,
        flexDirection: "row",
        alignItems: "center",
        gap: spacing.md,
        paddingHorizontal: spacing.md,
    },
    attachmentActionText: {
        color: "#1597DF",
        fontSize: 21,
        lineHeight: 26,
        fontWeight: "500",
    },
    attachmentActionDivider: {
        height: StyleSheet.hairlineWidth,
        marginLeft: 64,
        backgroundColor: "rgba(60,60,67,0.18)",
    },
    attachmentRecentTitle: {
        marginTop: spacing.lg,
        marginBottom: spacing.sm,
        color: "#8A8F96",
        fontSize: 14,
        lineHeight: 17,
        fontWeight: "700",
        letterSpacing: 0,
        textTransform: "uppercase",
    },
    fileRecentCard: {
        overflow: "hidden",
        borderRadius: 22,
        ...liquidGlassNeutral,
        ...glassShadow,
    },
    fileRecentRow: {
        minHeight: 66,
        flexDirection: "row",
        alignItems: "center",
        gap: spacing.sm,
        paddingHorizontal: spacing.md,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: "rgba(60,60,67,0.16)",
    },
    fileRecentIcon: {
        width: 34,
        height: 34,
        borderRadius: 10,
        backgroundColor: "rgba(21,151,223,0.11)",
        alignItems: "center",
        justifyContent: "center",
    },
    fileRecentTextWrap: {
        flex: 1,
    },
    fileRecentName: {
        color: "#0A0A0A",
        fontSize: 16,
        lineHeight: 20,
        fontWeight: "700",
    },
    fileRecentMeta: {
        marginTop: 2,
        color: "#7C858C",
        fontSize: 12,
        lineHeight: 15,
    },
    fileRecentEmpty: {
        color: "#7C858C",
        fontSize: 14,
        lineHeight: 20,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.md,
    },
    attachmentModeBar: {
        position: "absolute",
        left: spacing.md,
        right: spacing.md,
        zIndex: 7,
        minHeight: 76,
        borderRadius: 32,
        ...liquidGlassNeutral,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: spacing.xs,
        padding: 7,
        ...glassShadow,
    },
    attachmentModeButton: {
        flex: 1,
        height: 62,
        borderRadius: 26,
        alignItems: "center",
        justifyContent: "center",
        gap: 3,
    },
    attachmentModeButtonActive: {
        backgroundColor: "rgba(36,177,245,0.24)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.62)",
    },
    attachmentModeLabel: {
        color: "#24282C",
        fontSize: 12,
        lineHeight: 15,
        fontWeight: "700",
    },
    attachmentModeLabelActive: {
        color: colors.primary,
    },
    albumSelectorPopover: {
        position: "absolute",
        top: 82,
        alignSelf: "center",
        width: 264,
        maxHeight: 286,
        zIndex: 9,
        overflow: "hidden",
        borderRadius: 22,
        ...liquidGlassNeutral,
        ...glassShadow,
    },
    albumSelectorRow: {
        minHeight: 48,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: spacing.sm,
        paddingHorizontal: spacing.md,
    },
    albumSelectorRowActive: {
        backgroundColor: "rgba(21,151,223,0.12)",
    },
    albumSelectorText: {
        flex: 1,
        color: "#111417",
        fontSize: 16,
        lineHeight: 20,
        fontWeight: "700",
    },
    albumSelectorTextActive: {
        color: colors.primary,
    },
    albumSelectorCount: {
        color: "#7C858C",
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "700",
    },
})
