import { StyleSheet } from "react-native"
import type { ThemePalette } from "@/theme/colors"
import { spacing } from "@/theme/spacing"

export const createCommunityChatStyles = (colors: ThemePalette) => StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.surfaceSoft },
    overlay: { ...StyleSheet.absoluteFillObject, zIndex: 50 },
    hidden: { display: "none" },
    header: { position: "absolute", left: spacing.md, right: spacing.md, zIndex: 10, flexDirection: "row", alignItems: "center", gap: spacing.sm },
    backButton: { width: 48, height: 48, borderRadius: 24, alignItems: "center", justifyContent: "center", backgroundColor: colors.surfaceOverlay, borderColor: colors.borderSoft, borderWidth: 1, shadowColor: "#0C2A3A", shadowOpacity: 0.14, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 6 },
    backText: { color: colors.text, fontSize: 25, lineHeight: 27, fontWeight: "500" },
    modeSwitcher: { width: 208, height: 44, borderRadius: 23, padding: 3, flexDirection: "row", backgroundColor: colors.surfaceOverlaySoft, borderColor: colors.borderSoft, borderWidth: 1, overflow: "hidden", shadowColor: "#0C2A3A", shadowOpacity: 0.12, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
    modeIndicator: { position: "absolute", left: 3, top: 3, width: 98, height: 36, borderRadius: 19, backgroundColor: colors.primary },
    modeButton: { width: 101, height: 36, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 4, zIndex: 1 },
    modeText: { flexShrink: 1, color: colors.stateText, fontSize: 13, lineHeight: 16, fontWeight: "700" },
    modeTextActive: { color: colors.onPrimary },
    modeBadge: { minWidth: 18, height: 18, borderRadius: 9, paddingHorizontal: 4, alignItems: "center", justifyContent: "center", backgroundColor: colors.danger },
    modeBadgeText: { color: "#FFFFFF", fontSize: 10, lineHeight: 12, fontWeight: "800" },
    content: { flex: 1 },
    stateCenter: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: spacing.lg, gap: spacing.sm },
    stateIcon: { width: 72, height: 72, borderRadius: 36, alignItems: "center", justifyContent: "center", backgroundColor: colors.primaryMuted },
    stateIconText: { color: colors.primary, fontSize: 30, fontWeight: "800" },
    stateTitle: { color: colors.text, fontSize: 22, lineHeight: 28, fontWeight: "800", textAlign: "center" },
    stateBody: { color: colors.stateText, fontSize: 15, lineHeight: 21, textAlign: "center", maxWidth: 360 },
    primaryButton: { minHeight: 48, borderRadius: 24, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center", paddingHorizontal: spacing.lg, marginTop: spacing.xs },
    primaryButtonText: { color: colors.onPrimary, fontSize: 15, fontWeight: "800" },
    secondaryButton: { minHeight: 42, borderRadius: 21, backgroundColor: colors.surfaceElevated, alignItems: "center", justifyContent: "center", paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.border },
    secondaryButtonText: { color: colors.text, fontSize: 14, fontWeight: "700" },
    topicsContent: { paddingHorizontal: spacing.md, paddingBottom: 120, gap: spacing.sm },
    groupHero: { borderRadius: 24, backgroundColor: colors.surfaceOverlay, borderWidth: 1, borderColor: colors.borderSoft, padding: spacing.md, flexDirection: "row", alignItems: "center", gap: spacing.md },
    groupAvatar: { width: 58, height: 58, borderRadius: 29, backgroundColor: colors.primaryMuted },
    groupAvatarFallback: { alignItems: "center", justifyContent: "center" },
    groupAvatarText: { color: colors.primary, fontSize: 22, fontWeight: "900" },
    groupCopy: { flex: 1, gap: 3 },
    groupTitle: { color: colors.text, fontSize: 20, lineHeight: 25, fontWeight: "800" },
    groupSubtitle: { color: colors.stateText, fontSize: 13, lineHeight: 18 },
    sectionLabel: { color: colors.stateText, fontSize: 13, lineHeight: 17, fontWeight: "800", textTransform: "uppercase", letterSpacing: 0.7, marginTop: spacing.xs, marginLeft: 4 },
    topicCard: { minHeight: 82, borderRadius: 20, padding: 13, flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: colors.surfaceOverlay, borderWidth: 1, borderColor: colors.borderSoft },
    topicCardPressed: { opacity: 0.78 },
    topicIcon: { width: 48, height: 48, borderRadius: 16, alignItems: "center", justifyContent: "center" },
    topicIconText: { color: "#FFFFFF", fontSize: 20, fontWeight: "900" },
    topicCopy: { flex: 1, gap: 4 },
    topicTitleRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    topicTitle: { flex: 1, color: colors.text, fontSize: 16, lineHeight: 20, fontWeight: "800" },
    topicPreview: { color: colors.stateText, fontSize: 13, lineHeight: 18 },
    topicMeta: { alignItems: "flex-end", gap: 7 },
    topicTime: { color: colors.mutedText, fontSize: 11, lineHeight: 14 },
    unreadBadge: { minWidth: 24, height: 24, borderRadius: 12, alignItems: "center", justifyContent: "center", paddingHorizontal: 6, backgroundColor: colors.primary },
    unreadText: { color: colors.onPrimary, fontSize: 11, fontWeight: "900" },
    closedPill: { borderRadius: 9, paddingHorizontal: 6, paddingVertical: 2, backgroundColor: colors.surfaceMuted },
    closedText: { color: colors.stateText, fontSize: 10, fontWeight: "700" },
    topicHeader: { minHeight: 52, justifyContent: "center", paddingHorizontal: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.borderSoft, backgroundColor: colors.surfaceOverlaySoft },
    topicHeaderTitle: { color: colors.text, fontSize: 16, lineHeight: 20, fontWeight: "800" },
    topicHeaderStatus: { color: colors.stateText, fontSize: 12, lineHeight: 15 },
    messageScroll: { flex: 1 },
    messageContent: { flexGrow: 1, justifyContent: "flex-end", paddingHorizontal: spacing.sm, gap: 9 },
    loadOlder: { alignSelf: "center", minHeight: 34, justifyContent: "center", paddingHorizontal: 14, borderRadius: 17, backgroundColor: colors.surfaceOverlay },
    loadOlderText: { color: colors.primary, fontSize: 13, fontWeight: "700" },
    messageRow: { flexDirection: "row", alignItems: "flex-end", gap: 7 },
    messageRowMine: { flexDirection: "row-reverse" },
    authorAvatar: { width: 32, height: 32, borderRadius: 16, backgroundColor: colors.primaryMuted },
    avatarFallback: { alignItems: "center", justifyContent: "center" },
    avatarInitials: { color: colors.primary, fontSize: 11, fontWeight: "900" },
    messageBubble: { maxWidth: "78%", borderRadius: 18, borderBottomLeftRadius: 7, paddingHorizontal: 11, paddingVertical: 8, gap: 5, backgroundColor: colors.surfaceOverlay, borderWidth: 1, borderColor: colors.borderSoft },
    messageBubbleMine: { borderBottomLeftRadius: 18, borderBottomRightRadius: 7, backgroundColor: colors.primaryMuted, borderColor: colors.primaryMuted },
    authorName: { color: colors.primary, fontSize: 12, lineHeight: 15, fontWeight: "800" },
    replyPreview: { borderLeftWidth: 3, borderLeftColor: colors.primary, borderRadius: 6, backgroundColor: colors.veil, paddingHorizontal: 8, paddingVertical: 5 },
    replyAuthor: { color: colors.primary, fontSize: 11, lineHeight: 14, fontWeight: "800" },
    replyText: { color: colors.stateText, fontSize: 11, lineHeight: 15 },
    messageText: { color: colors.text, fontSize: 15, lineHeight: 21 },
    messageImage: { width: 220, height: 170, borderRadius: 13, backgroundColor: colors.surfaceMuted },
    documentCard: { minHeight: 46, borderRadius: 12, paddingHorizontal: 9, flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: colors.surfaceMuted },
    documentIcon: { color: colors.primary, fontSize: 20 },
    documentName: { flex: 1, color: colors.text, fontSize: 13, lineHeight: 17, fontWeight: "700" },
    unsupportedCard: { borderRadius: 12, backgroundColor: colors.warningMuted, padding: 9, gap: 5 },
    unsupportedText: { color: colors.warning, fontSize: 12, lineHeight: 16 },
    telegramLink: { color: colors.primary, fontSize: 12, lineHeight: 16, fontWeight: "800" },
    messageMeta: { color: colors.mutedText, fontSize: 10, lineHeight: 13, alignSelf: "flex-end" },
    composer: { position: "absolute", left: 0, right: 0, bottom: 0, paddingHorizontal: spacing.sm, paddingTop: spacing.xs, backgroundColor: colors.surfaceOverlaySoft, borderTopWidth: 1, borderTopColor: colors.borderSoft },
    replyComposer: { minHeight: 46, borderRadius: 13, backgroundColor: colors.surfaceMuted, paddingHorizontal: 10, paddingVertical: 6, flexDirection: "row", alignItems: "center", gap: 8 },
    replyComposerCopy: { flex: 1 },
    replyComposerTitle: { color: colors.primary, fontSize: 11, fontWeight: "800" },
    replyComposerText: { color: colors.stateText, fontSize: 11 },
    closeReply: { color: colors.stateText, fontSize: 22 },
    attachmentStrip: { flexDirection: "row", gap: 6, paddingBottom: 6 },
    queuedAttachment: { maxWidth: 160, minHeight: 32, borderRadius: 16, backgroundColor: colors.surfaceMuted, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", gap: 5 },
    queuedAttachmentName: { flex: 1, color: colors.text, fontSize: 11 },
    queuedAttachmentRemove: { color: colors.danger, fontSize: 17 },
    composerRow: { flexDirection: "row", alignItems: "flex-end", gap: 7 },
    composerButton: { width: 46, height: 46, borderRadius: 23, alignItems: "center", justifyContent: "center", backgroundColor: colors.surfaceElevated, borderWidth: 1, borderColor: colors.border },
    composerButtonText: { color: colors.primary, fontSize: 24, fontWeight: "500" },
    composerInput: { flex: 1, maxHeight: 112, minHeight: 46, borderRadius: 23, paddingHorizontal: 15, paddingTop: 12, paddingBottom: 10, color: colors.text, backgroundColor: colors.fieldBackground, borderWidth: 1, borderColor: colors.borderSoft, fontSize: 15, lineHeight: 20 },
    sendButton: { width: 46, height: 46, borderRadius: 23, alignItems: "center", justifyContent: "center", backgroundColor: colors.primary },
    sendButtonDisabled: { opacity: 0.45 },
    sendButtonText: { color: colors.onPrimary, fontSize: 20, fontWeight: "900" },
    inlineError: { marginHorizontal: spacing.md, marginBottom: spacing.xs, borderRadius: 12, padding: 9, backgroundColor: colors.dangerMuted },
    inlineErrorText: { color: colors.danger, fontSize: 12, textAlign: "center" },
})
