// Run with ESBUILD_PATH and PLAYWRIGHT_PATH pointing to test-only dependencies.
const path = require("node:path")
const fs = require("node:fs")
const http = require("node:http")
const assert = require("node:assert/strict")
const esbuild = require(process.env.ESBUILD_PATH || "esbuild")
const { chromium } = require(process.env.PLAYWRIGHT_PATH || "playwright")
const root = path.resolve(__dirname, "..")
const fixture = path.join(__dirname, "mentor-preview.jsx")
const aliases = ["@/services/api/companion", "@/providers/theme-provider", "expo-router"]
async function main() {
    const build = await esbuild.build({ entryPoints: [fixture], bundle: true, write: false, format: "iife", jsx: "automatic", loader: { ".js": "jsx", ".png": "dataurl" }, platform: "browser", define: { "process.env.NODE_ENV": '"development"', __DEV__: "true" }, resolveExtensions: [".web.js", ".js", ".tsx", ".ts", ".jsx"], alias: { "react-native": "react-native-web", "react-native-svg": path.join(root, "node_modules/react-native-svg/lib/module/ReactNativeSVG.web.js") }, plugins: [{ name: "test-only-api", setup(build) {
        build.onResolve({ filter: /^(?:@\/|expo-router$)/ }, args => aliases.includes(args.path) ? { path: fixture } : { path: path.join(root, args.path.slice(2)) + (fs.existsSync(path.join(root, args.path.slice(2))) ? "" : fs.existsSync(path.join(root, args.path.slice(2)) + ".tsx") ? ".tsx" : ".ts") })
        build.onLoad({ filter: /\.svg$/ }, args => ({ loader: "jsx", contents: `import React from 'react';export default function Icon(props){return <img alt="" width={props.width} height={props.height} src=${JSON.stringify("data:image/svg+xml;base64," + fs.readFileSync(args.path).toString("base64"))}/>}` }))
    } }] })
    const server = http.createServer((req, res) => { res.setHeader("Content-Type", req.url === "/bundle.js" ? "text/javascript" : "text/html"); res.end(req.url === "/bundle.js" ? build.outputFiles[0].contents : '<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><body style="margin:0"><div id="root"></div><script src="/bundle.js"></script></body></html>') })
    await new Promise(resolve => server.listen(0, "127.0.0.1", resolve))
    const browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}) })
    const errors = []
    try {
        for (const width of [390, 1280]) {
            const page = await browser.newPage({ viewport: { width, height: 844 } })
            page.on("pageerror", error => errors.push(error.message))
            page.on("dialog", dialog => dialog.accept())
            await page.goto(`http://127.0.0.1:${server.address().port}`)
            await page.getByText("Ваш план на сегодня", { exact: true }).waitFor()
            assert.equal(await page.getByText("Выполнено 0 из 1 запланированных событий", { exact: true }).count(), 1)
            await page.screenshot({ path: `/tmp/mentor-today-${width}.png`, fullPage: true })
            await page.getByRole("button", { name: "Добавить еду", exact: true }).click()
            await page.getByRole("button", { name: "Фото еды", exact: true }).waitFor()
            await page.getByRole("button", { name: "Повторить", exact: true }).click()
            await page.getByRole("button", { name: "Отмена", exact: true }).click()
            assert.equal(await page.evaluate(() => window.__mentor.store.actions.filter(action => action.kind === "entry").length), 0)
            await page.getByRole("button", { name: "В избранное", exact: true }).click()
            await page.getByRole("tab", { name: "Избранное", exact: true }).click()
            await page.getByText("Тестовый обед", { exact: true }).waitFor()
            await page.getByRole("tab", { name: "Тренировки", exact: true }).click()
            await page.getByRole("button", { name: "Изменить план недели", exact: true }).click()
            await page.getByLabel("Название плана", { exact: true }).fill("Обновлённый тестовый план")
            await page.getByRole("button", { name: "Сохранить план недели", exact: true }).click()
            assert.equal(await page.evaluate(() => window.__mentor.store.actions.find(action => action.kind === "workout_plan").expected_version), 1)
            await page.getByRole("button", { name: "Начать тренировку", exact: true }).click()
            await page.getByLabel("Вес, кг", { exact: true }).first().fill("20.5")
            await page.getByLabel("Повторения", { exact: true }).first().fill("8")
            await page.getByLabel("Подход 1 выполнен", { exact: true }).check()
            await page.getByRole("button", { name: "Сохранить подходы", exact: true }).click()
            await page.screenshot({ path: `/tmp/mentor-workout-${width}.png` })
            await page.getByRole("button", { name: "Завершить тренировку", exact: true }).click()
            await page.getByText("Завершена", { exact: true }).waitFor()
            const workout = await page.evaluate(() => window.__mentor.store.entries.find(entry => entry.kind === "workout").data.workout)
            assert.equal(workout.status, "completed")
            assert.equal(workout.exercises[0].sets[1].completed, false)
            await page.evaluate(() => window.__mentor.setMentorPage("progress"))
            await page.getByText("Прогресс за 7 дней", { exact: true }).waitFor()
            await page.screenshot({ path: `/tmp/mentor-progress-${width}.png`, fullPage: true })
            assert.ok(await page.locator("svg polyline").count())
            await page.getByRole("button", { name: "Добавить вес", exact: true }).scrollIntoViewIfNeeded()
            const addWeight = await page.getByRole("button", { name: "Добавить вес", exact: true }).boundingBox()
            const nav = await page.getByTestId("fixture-navigation").boundingBox()
            assert.ok(addWeight.y + addWeight.height <= nav.y, "Navigation must not cover the final action")
            await page.screenshot({ path: `/tmp/mentor-progress-actions-${width}.png` })
            await page.getByRole("tab", { name: "Питание", exact: true }).first().click()
            await page.getByText("9800 ккал записано", { exact: true }).waitFor()
            assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false)
            await page.getByRole("tab", { name: "Замеры", exact: true }).click()
            await page.getByRole("button", { name: "Добавить замеры", exact: true }).click()
            await page.getByLabel("Талия, см", { exact: true }).fill("81.5")
            await page.getByRole("button", { name: "Подтвердить замеры", exact: true }).click()
            assert.equal(await page.evaluate(() => window.__mentor.store.entries.find(entry => entry.kind === "measurement").data.measurement.waist_cm), "81.5")
            await page.getByRole("tab", { name: "Фото", exact: true }).click()
            await page.getByRole("button", { name: "Сохранить в прогресс", exact: true }).click()
            await page.getByRole("button", { name: "Отмена", exact: true }).click()
            assert.equal(await page.evaluate(() => window.__mentor.store.entries.filter(entry => entry.kind === "progress_photo").length), 0)
            await page.getByRole("button", { name: "Сохранить в прогресс", exact: true }).click()
            await page.getByRole("button", { name: "Подтвердить сохранение фото", exact: true }).click()
            assert.deepEqual(await page.evaluate(() => window.__mentor.store.entries.find(entry => entry.kind === "progress_photo").data.photo_attachment_ids), [301])
            await page.getByRole("button", { name: "Добавить фото прогресса", exact: true }).click()
            const action = await page.evaluate(() => window.__mentor.store.actions.at(-1))
            assert.equal(action.compose, "photo")
            assert.match(action.text, /^Фото прогресса\./)
            assert.doesNotMatch(action.text, /еду|порци/)
            await page.close()
        }
        assert.deepEqual(errors, [])
        console.log("Mentor mobile/desktop controls passed; screenshots: /tmp/mentor-{today,progress}-{390,1280}.png")
    } finally { await browser.close(); await new Promise(resolve => server.close(resolve)) }
}
main().catch(error => { console.error(error); process.exitCode = 1 })
