"""add ai chat tables

Revision ID: 27d03a60b2ea
Revises: c4f1a7d9e2b3
Create Date: 2026-04-30 18:24:26.915763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27d03a60b2ea'
down_revision: Union[str, Sequence[str], None] = 'c4f1a7d9e2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('current_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=True)
    op.create_table('ai_messages',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sender', sa.Enum('user', 'ai', name='message_sender'), nullable=False),
    sa.Column('bot_model', sa.Enum('free', 'premium', name='bot_model'), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_chat_id'), 'ai_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_id'), 'ai_messages', ['id'], unique=False)
    op.create_index(op.f('ix_ai_messages_user_id'), 'ai_messages', ['user_id'], unique=False)
    op.create_table('attachments',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('document', 'image', name='attachment_type'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['ai_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    op.create_index(op.f('ix_attachments_message_id'), 'attachments', ['message_id'], unique=False)
    op.drop_index(op.f('ix_yandex_door_addresses_country_code'), table_name='yandex_door_addresses')
    op.drop_index(op.f('ix_yandex_door_addresses_id'), table_name='yandex_door_addresses')
    op.drop_index(op.f('ix_yandex_door_addresses_name'), table_name='yandex_door_addresses')
    op.drop_index(op.f('ix_yandex_door_addresses_provider'), table_name='yandex_door_addresses')
    op.drop_index(op.f('ix_yandex_door_addresses_user_id'), table_name='yandex_door_addresses')
    op.drop_table('yandex_door_addresses')
    op.drop_constraint(op.f('user_push_tokens_expo_push_token_key'), 'user_push_tokens', type_='unique')
    op.drop_index(op.f('ix_user_push_tokens_expo_push_token'), table_name='user_push_tokens')
    op.create_index(op.f('ix_user_push_tokens_expo_push_token'), 'user_push_tokens', ['expo_push_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_push_tokens_expo_push_token'), table_name='user_push_tokens')
    op.create_index(op.f('ix_user_push_tokens_expo_push_token'), 'user_push_tokens', ['expo_push_token'], unique=False)
    op.create_unique_constraint(op.f('user_push_tokens_expo_push_token_key'), 'user_push_tokens', ['expo_push_token'], postgresql_nulls_not_distinct=False)
    op.create_table('yandex_door_addresses',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('country_code', postgresql.ENUM('RU', 'BY', 'KZ', 'AZ', 'MD', 'AM', 'UZ', 'KG', 'GE', 'MN', 'CN', 'JP', 'RS', 'IL', 'AE', 'IN', 'BD', 'VN', 'TH', 'ID', 'US', name='country_code_enum'), autoincrement=False, nullable=False),
    sa.Column('provider', postgresql.ENUM('YANDEX', 'CDEK', name='delivery_provider_enum'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('full_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('yandex_door_addresses_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('yandex_door_addresses_pkey'))
    )
    op.create_index(op.f('ix_yandex_door_addresses_user_id'), 'yandex_door_addresses', ['user_id'], unique=False)
    op.create_index(op.f('ix_yandex_door_addresses_provider'), 'yandex_door_addresses', ['provider'], unique=False)
    op.create_index(op.f('ix_yandex_door_addresses_name'), 'yandex_door_addresses', ['name'], unique=False)
    op.create_index(op.f('ix_yandex_door_addresses_id'), 'yandex_door_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_yandex_door_addresses_country_code'), 'yandex_door_addresses', ['country_code'], unique=False)
    op.drop_index(op.f('ix_attachments_message_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_ai_messages_user_id'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_id'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_chat_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
