"""add website website_identity

Revision ID: 2fac1df2cc97
Revises: b1ab802b09b6
Create Date: 2026-03-22 15:47:30.096462

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fac1df2cc97"
down_revision: Union[str, Sequence[str], None] = "b1ab802b09b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "website_identities",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("website_user_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_website_identities_id"), "website_identities", ["id"], unique=False)
    op.create_index(op.f("ix_website_identities_user_id"), "website_identities", ["user_id"], unique=True)
    op.create_index(op.f("ix_website_identities_website_user_id"), "website_identities", ["website_user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_website_identities_website_user_id"), table_name="website_identities")
    op.drop_index(op.f("ix_website_identities_user_id"), table_name="website_identities")
    op.drop_index(op.f("ix_website_identities_id"), table_name="website_identities")
    op.drop_table("website_identities")
    # ### end Alembic commands ###
