"""sync delivery address schema with models

Revision ID: aa833c6f3f6f
Revises: f0f46420ee89
Create Date: 2026-04-20 17:37:23.868623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa833c6f3f6f'
down_revision: Union[str, Sequence[str], None] = 'f0f46420ee89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cdek_door_addresses', 'comment')
    op.drop_column('cdek_door_addresses', 'shipment_point')
    op.drop_column('cdek_pickup_addresses', 'comment')
    op.drop_column('cdek_pickup_addresses', 'shipment_point')
    op.add_column('yandex_door_addresses', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('yandex_door_addresses', sa.Column('longitude', sa.Float(), nullable=False))
    op.drop_column('yandex_door_addresses', 'comment')
    op.drop_column('yandex_door_addresses', 'shipment_point')
    op.add_column('yandex_pickup_addresses', sa.Column('platform_id', sa.UUID(), nullable=False))
    op.drop_column('yandex_pickup_addresses', 'comment')
    op.drop_column('yandex_pickup_addresses', 'delivery_point')
    op.drop_column('yandex_pickup_addresses', 'shipment_point')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yandex_pickup_addresses', sa.Column('shipment_point', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('yandex_pickup_addresses', sa.Column('delivery_point', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('yandex_pickup_addresses', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('yandex_pickup_addresses', 'platform_id')
    op.add_column('yandex_door_addresses', sa.Column('shipment_point', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('yandex_door_addresses', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('yandex_door_addresses', 'longitude')
    op.drop_column('yandex_door_addresses', 'latitude')
    op.add_column('cdek_pickup_addresses', sa.Column('shipment_point', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('cdek_pickup_addresses', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('cdek_door_addresses', sa.Column('shipment_point', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('cdek_door_addresses', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
