"""add users sessions and string limits

Revision ID: b1ab802b09b6
Revises: 99f04b88563a
Create Date: 2026-03-21 16:39:00.980385

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1ab802b09b6"
down_revision: Union[str, Sequence[str], None] = "99f04b88563a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("products", "sku", existing_type=sa.VARCHAR(), type_=sa.String(length=64), existing_nullable=False)
    op.alter_column("products", "name", existing_type=sa.VARCHAR(), type_=sa.String(length=200), existing_nullable=False)
    op.alter_column("products", "description", existing_type=sa.VARCHAR(), type_=sa.String(length=5000), existing_nullable=True)
    op.alter_column("products", "usage", existing_type=sa.VARCHAR(), type_=sa.String(length=2000), existing_nullable=True)
    op.alter_column("products", "expiration", existing_type=sa.VARCHAR(), type_=sa.String(length=1000), existing_nullable=True)
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=16), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("surname", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "user_sessions",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_sessions_id"), "user_sessions", ["id"], unique=False)
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.alter_column("products", "expiration", existing_type=sa.String(length=1000), type_=sa.VARCHAR(), existing_nullable=True)
    op.alter_column("products", "usage", existing_type=sa.String(length=2000), type_=sa.VARCHAR(), existing_nullable=True)
    op.alter_column("products", "description", existing_type=sa.String(length=5000), type_=sa.VARCHAR(), existing_nullable=True)
    op.alter_column("products", "name", existing_type=sa.String(length=200), type_=sa.VARCHAR(), existing_nullable=False)
    op.alter_column("products", "sku", existing_type=sa.String(length=64), type_=sa.VARCHAR(), existing_nullable=False)
    # ### end Alembic commands ###
