from cryptography.x509.oid import ObjectIdentifier

from config import (
    APP_INTEGRITY_ANDROID_ALLOWED_DEVICE_VERDICTS,
    APP_INTEGRITY_ANDROID_CERT_SHA256_DIGESTS,
    APP_INTEGRITY_ANDROID_PACKAGE_NAME,
    APP_INTEGRITY_CHALLENGE_TTL_SECONDS,
    APP_INTEGRITY_DEV_TOKEN,
    APP_INTEGRITY_IOS_ALLOWED_ENVIRONMENTS,
    APP_INTEGRITY_IOS_BUNDLE_ID,
    APP_INTEGRITY_IOS_TEAM_ID,
    APP_INTEGRITY_MODE,
    APP_INTEGRITY_TOKEN_MAX_AGE_SECONDS,
    APP_INTEGRITY_VERIFIER_TIMEOUT_SECONDS,
    APP_INTEGRITY_VERIFIER_URL,
)

APP_INTEGRITY_TOKEN_HEADER = "x-app-integrity-token"
APP_INTEGRITY_PLATFORM_HEADER = "x-app-integrity-platform"
APP_INTEGRITY_ACTION_HEADER = "x-app-integrity-action"
APP_INTEGRITY_REQUEST_HASH_HEADER = "x-app-integrity-request-hash"
APP_INTEGRITY_KEY_ID_HEADER = "x-app-integrity-key-id"
APP_INTEGRITY_MODES = {"off", "monitor", "enforce"}
PLAY_INTEGRITY_SCOPE = "https://www.googleapis.com/auth/playintegrity"
APPLE_APP_ATTEST_NONCE_OID = ObjectIdentifier("1.2.840.113635.100.8.2")
APPLE_APP_ATTEST_AAGUIDS = {
    "production": b"appattest" + (b"\x00" * 7),
    "development": b"appattestdevelop",
    "sandbox": b"appattestsandbox",
}

__all__ = [
    "APP_INTEGRITY_ACTION_HEADER",
    "APP_INTEGRITY_ANDROID_ALLOWED_DEVICE_VERDICTS",
    "APP_INTEGRITY_ANDROID_CERT_SHA256_DIGESTS",
    "APP_INTEGRITY_ANDROID_PACKAGE_NAME",
    "APP_INTEGRITY_CHALLENGE_TTL_SECONDS",
    "APP_INTEGRITY_DEV_TOKEN",
    "APP_INTEGRITY_IOS_ALLOWED_ENVIRONMENTS",
    "APP_INTEGRITY_IOS_BUNDLE_ID",
    "APP_INTEGRITY_IOS_TEAM_ID",
    "APP_INTEGRITY_KEY_ID_HEADER",
    "APP_INTEGRITY_MODE",
    "APP_INTEGRITY_MODES",
    "APP_INTEGRITY_PLATFORM_HEADER",
    "APP_INTEGRITY_REQUEST_HASH_HEADER",
    "APP_INTEGRITY_TOKEN_HEADER",
    "APP_INTEGRITY_TOKEN_MAX_AGE_SECONDS",
    "APP_INTEGRITY_VERIFIER_TIMEOUT_SECONDS",
    "APP_INTEGRITY_VERIFIER_URL",
    "APPLE_APP_ATTEST_AAGUIDS",
    "APPLE_APP_ATTEST_NONCE_OID",
    "PLAY_INTEGRITY_SCOPE",
]
