export const IMAGE_CAROUSEL_AUTO_SCROLL_INTERVAL_MS = 2500
export const IMAGE_CAROUSEL_CARD_GAP = 12
export const IMAGE_CAROUSEL_MAX_CARD_WIDTH = 160
export const IMAGE_CAROUSEL_VISIBLE_CARD_COUNT = 3
